### ISSUE TITLE
[HASS_API] Error while fetching HA config

### ISSUE THREAD

**Issue by warlordattack** [LAB02-Research/HASS.Agent#125]
Hello i recently changed from docker to vmm home assitant, and changed config in HASS.Agent : 
new connexion infos and api token.

Everything works, i have notifications and stats from my PC,
but home assistant api says : connecting and is stuck.

I used : 
http://192.168.1.85:8123

and new api token generated on the new server : oT1_nUtFBescoHMGxRZXFEEI7lmijVTDskOeS4h4d3A
no client cert

I tryed http://192.168.1.85:8123 and 192.168.1.85:8123 : none works.
when i test connexion it says : unable to connect check uri and config.

![2022-07-19_171312](https://user-images.githubusercontent.com/3226486/179785711-2c6ea6c8-a8b2-414d-93b3-6bcc91e5ca7a.jpg)

```
2022-07-19 16:33:50.537 +02:00 [INF] [SETTINGS] Config storage path: C:\Users\alexe\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-07-19 16:33:50.624 +02:00 [INF] [SETTINGS] Configuration loaded
2022-07-19 16:33:50.627 +02:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-07-19 16:33:50.895 +02:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2022-07-19 16:33:50.922 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2022-07-19 16:34:02.311 +02:00 [INF] [SETTINGS_SENSORS] Loaded 11 entities
2022-07-19 16:34:02.318 +02:00 [INF] [MQTT] Identifying as device: ant
2022-07-19 16:34:02.318 +02:00 [INF] [LOCALAPI] Initializing ..
2022-07-19 16:34:02.318 +02:00 [INF] [NOTIFIER] Ready
2022-07-19 16:34:02.319 +02:00 [INF] [MEDIA] Ready
2022-07-19 16:34:02.319 +02:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-07-19 16:34:02.322 +02:00 [FTL] [HASS_API] Error while initializing client: Invalid URI: The URI scheme is not valid.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at HASS.Agent.HomeAssistant.HassApiManager.InitializeClient()
2022-07-19 16:34:02.323 +02:00 [INF] [MQTT] Connecting ..
2022-07-19 16:34:02.384 +02:00 [INF] [MQTT] Connected
2022-07-19 16:34:02.549 +02:00 [INF] [LOCALAPI] listening on port 5115
2022-07-19 16:34:04.329 +02:00 [INF] [MQTT] Initial registration completed
2022-07-19 16:52:07.194 +02:00 [FTL] [HASS_API] Error while checking config: Invalid URI: The URI scheme is not valid.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at HADotNet.Core.ClientFactory.Initialize(String instanceAddress, String apiKey)
   at HASS.Agent.HomeAssistant.HassApiManager.CheckHassConfigAsync(String uri, String apiKey, Boolean automaticClientCertificate, String clientCertificate)
2022-07-19 16:52:32.248 +02:00 [FTL] [HASS_API] Error while checking config: Response status code does not indicate success: 401 (Unauthorized).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Get[T](String path)
   at HADotNet.Core.Clients.ConfigClient.GetConfiguration()
   at HASS.Agent.HomeAssistant.HassApiManager.CheckHassConfigAsync(String uri, String apiKey, Boolean automaticClientCertificate, String clientCertificate)
2022-07-19 16:53:44.346 +02:00 [FTL] [HASS_API] Error while checking config: Invalid URI: The URI scheme is not valid.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at HADotNet.Core.ClientFactory.Initialize(String instanceAddress, String apiKey)
   at HASS.Agent.HomeAssistant.HassApiManager.CheckHassConfigAsync(String uri, String apiKey, Boolean automaticClientCertificate, String clientCertificate)
2022-07-19 16:53:59.179 +02:00 [FTL] [HASS_API] Error while checking config: Response status code does not indicate success: 401 (Unauthorized).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Get[T](String path)
   at HADotNet.Core.Clients.ConfigClient.GetConfiguration()
   at HASS.Agent.HomeAssistant.HassApiManager.CheckHassConfigAsync(String uri, String apiKey, Boolean automaticClientCertificate, String clientCertificate)
2022-07-19 16:56:53.440 +02:00 [INF] [SETTINGS] Configuration stored
2022-07-19 16:56:55.325 +02:00 [INF] [SYSTEM] Application shutting down
2022-07-19 16:56:55.328 +02:00 [INF] [MQTT] Disconnected
2022-07-19 16:56:55.349 +02:00 [INF] [SYSTEM] Application shutdown complete
2022-07-19 16:56:57.379 +02:00 [INF] [SETTINGS] Config storage path: C:\Users\alexe\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-07-19 16:56:57.473 +02:00 [INF] [SETTINGS] Configuration loaded
2022-07-19 16:56:57.476 +02:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-07-19 16:56:57.701 +02:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2022-07-19 16:56:57.723 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2022-07-19 16:57:09.665 +02:00 [INF] [SETTINGS_SENSORS] Loaded 11 entities
2022-07-19 16:57:09.670 +02:00 [INF] [LOCALAPI] Initializing ..
2022-07-19 16:57:09.670 +02:00 [INF] [NOTIFIER] Ready
2022-07-19 16:57:09.671 +02:00 [INF] [MQTT] Identifying as device: ant
2022-07-19 16:57:09.671 +02:00 [INF] [MEDIA] Ready
2022-07-19 16:57:09.671 +02:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-07-19 16:57:09.676 +02:00 [INF] [MQTT] Connecting ..
2022-07-19 16:57:09.753 +02:00 [INF] [MQTT] Connected
2022-07-19 16:57:09.898 +02:00 [INF] [LOCALAPI] listening on port 5115
2022-07-19 16:57:11.691 +02:00 [INF] [MQTT] Initial registration completed
2022-07-19 16:58:10.546 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 16:59:10.876 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 17:00:11.474 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 17:01:11.899 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 17:02:12.271 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 17:03:12.637 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 17:04:13.014 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).
2022-07-19 17:05:13.555 +02:00 [FTL] [HASS_API] Error while fetching HA config: Response status code does not indicate success: 401 (Unauthorized).

```

**Comment by warlordattack** [comment]
Ok i found what happened : 
When you generate Long-Lived Access Tokens in the Home Assistant > user account (bottom of the page),
It diplays token you must copy-paste to the HASS.Agent app settings.

Pay attention : 
If you double click token to select it with your mouse, it selects only little part of it, not the entire string !!!!
Then you copy-past this incomplete selected key and it doesn't work.

Solution : 
Instead of double-click, use CTRL+A, then copy-paste to HASS.Agent, and it will be OK.
Same issue with vs-code and all other apps : if you copy-paste incomplete key it will not work.

This is very catchy because on the screen you don't see the entire key : because the input box is too small.

![2022-07-21_163342](https://user-images.githubusercontent.com/3226486/180240503-11a349f0-1ab3-4af1-ad03-f3b2bc419b82.jpg)
