### ISSUE TITLE
Bug: Updating to 2022.13.0-beta1 breaks MQTT connection

### ISSUE THREAD

**Issue by Draghmar** [LAB02-Research/HASS.Agent#137]
**Describe the bug**
Wanted to test something on beta branch but I can't because after updating MQTT can't connect. See the logs because that's the only thing I can provide in this case. :P

**Misc info (please complete the following information):**
 - Windows build: Win10 Pro - 21H2, 19044.1865
 - Windows' UI language: PL
 - HASS.Agent version: 2022.13.0-beta1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
```

2022-08-05 09:49:42.189 +02:00 [INF] [SYSTEM] Application shutdown complete
2022-08-05 09:49:44.462 +02:00 [INF] [MAIN] Extended logging enabled
2022-08-05 09:49:44.467 +02:00 [INF] [SETTINGS] Config storage path: C:\Users\---\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-08-05 09:49:44.614 +02:00 [INF] [SETTINGS] Configuration loaded
2022-08-05 09:49:44.618 +02:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-08-05 09:49:45.017 +02:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2022-08-05 09:49:45.066 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 4 entities
2022-08-05 09:49:45.080 +02:00 [INF] [SETTINGS_SENSORS] Loaded 1 entities
2022-08-05 09:49:45.093 +02:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-08-05 09:49:45.098 +02:00 [INF] [LOCALAPI] Initializing ..
2022-08-05 09:49:45.098 +02:00 [INF] [NOTIFIER] Disabled
2022-08-05 09:49:45.098 +02:00 [INF] [MEDIA] Disabled
2022-08-05 09:49:45.101 +02:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2022-08-05 09:49:45.102 +02:00 [INF] [MQTT] Identifying as device: EARTH
2022-08-05 09:49:45.113 +02:00 [INF] [MQTT] Connecting ..
2022-08-05 09:49:45.267 +02:00 [INF] [HASS_API] Home Assistant version: 2022.8.1
2022-08-05 09:49:45.450 +02:00 [INF] [LOCALAPI] listening on port 5115
2022-08-05 09:49:45.584 +02:00 [INF] [HASS_API] System connected with ---
2022-08-05 09:49:55.165 +02:00 [FTL] [NET] [OperationAborted] Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
System.Net.Sockets.SocketException (995): Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2022-08-05 09:49:55.167 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2022-08-05 09:50:10.214 +02:00 [FTL] [NET] [OperationAborted] Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
System.Net.Sockets.SocketException (995): Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-08-05 09:50:10.214 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-08-05 09:50:25.249 +02:00 [FTL] [NET] [OperationAborted] Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
System.Net.Sockets.SocketException (995): Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2022-08-05 09:50:25.250 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-08-05 09:50:40.294 +02:00 [FTL] [NET] [OperationAborted] Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
System.Net.Sockets.SocketException (995): Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2022-08-05 09:50:40.295 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

**Comment by Draghmar** [comment]
Hm...downgrading to stable didn't help here so the issue may be in a different place. But I have no idea where. It was working right before the update...

**Comment by Draghmar** [comment]
My investigation took me to router settings, where I *probably* found culprit: I didn't forward MQTT port in firewall so when I wan connecting through VPN with split DNS, it couldn't connect. Not sure why it was working before though. Maybe I changed something...I can't believe it wasn't connected and I simply didn't notice that because I'm more often connected through VPN then not....
Anyway, I'll check how it work now and let you know if anything changes.

**Comment by Draghmar** [comment]
Ok, after few hours of checking if everything works as it should, I can assume it was DNS thing. Still not sure how it worked before though...
