### ISSUE TITLE
Bug: Home Assistant API connects only via external url. Failed for local ip.

### ISSUE THREAD

**Issue by pleaseRedo** [LAB02-Research/HASS.Agent#143]
**Describe the bug**
I get the API token and entered lan ip for my home assistant, the connection test failed. 

I then tried external domain: xxx.duckdns.org which passed the connection test.

**Screenshots**
![WeChat Image_20220813230854](https://user-images.githubusercontent.com/14801667/184500003-26cc2fd5-b5fc-4d2f-aad6-fe224bfef047.jpg)
![WeChat Image_20220813230907](https://user-images.githubusercontent.com/14801667/184500007-4db55827-cdf9-460e-9bce-a77150de3692.jpg)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output):  Version 22H2 (OS Build 22622.575)
 - Windows' UI language:  English
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**

>2022-08-13 23:07:04.172 +08:00 [FTL] [HASS_API] Error while fetching HA config: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
2022-08-13 23:07:07.459 +08:00 [INF] [HASS_API] Server recovered from failed state
2022-08-13 23:07:14.345 +08:00 [FTL] [HASS_API] Error while checking config: The SSL connection could not be established, see inner exception.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at HADotNet.Core.BaseClient.Get[T](String path)
   at HADotNet.Core.Clients.ConfigClient.GetConfiguration()
   at HASS.Agent.HomeAssistant.HassApiManager.CheckHassConfigAsync(String uri, String apiKey, Boolean automaticClientCertificate, String clientCertificate)

**Comment by LAB02-Admin** [comment]
That's because HA stops listening to its internal IP if you have duckdns setup. If you want it to listen to both, you can follow this guide:

https://hassagent.readthedocs.io/en/latest/notifications/notification-debugging-ssl/
