### ISSUE TITLE
Bug: Cannot run quick action automation

### ISSUE THREAD

**Issue by rolandorojas** [LAB02-Research/HASS.Agent#146]
I am trying to fire an automation action from quick actions. However, the automation never fires. I tried changing the desired action and changing triggers in HASS. Nothing seems to work. If I run the automation actions from HASS, they run as expected. 

**To Reproduce**
1. Go to Hass Agent and open Quick Actions
2. Create a new action to run an Automation. Set the desired action to anything. 
3. Save and try previewing the action
4. See error or just that nothing happens

**Expected behavior**
The automation actions should run. 

**Screenshots**
My action
![image](https://user-images.githubusercontent.com/31487237/185632038-da4fb564-d0f3-4357-aa8b-8fdaf7ff3b14.png)

My automation
![image](https://user-images.githubusercontent.com/31487237/185631488-72ccf383-6d7c-494e-a7c0-d4ed4efdadc4.png)

**Misc info (please complete the following information):**
 - Windows build
![image](https://user-images.githubusercontent.com/31487237/185631685-75bc8455-3011-4e4d-8826-faf206989127.png)

 - Windows' UI language: English US
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [x] Problem occurs in HASS.Agent

**Logs**
```
2022-08-19 09:32:01.987 -04:00 [INF] [HASS_API] [automation.turn_on_off_office_tv_from_jarvis] Performing action: open_cover
2022-08-19 09:32:01.999 -04:00 [FTL] [HASS_API] [automation.turn_on_off_office_tv_from_jarvis] Error while processing action: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
```

**Comment by tmeekes** [comment]
I'm having a similar issue... though for the 3 quick actions I've set up... the first one I entered works, but the other two won't. If I delete them and re-set them all up again, the first one I enter seems to be the one that works, even if I switch up the order of entering them.

**Comment by LAB02-Admin** [comment]
Is the `home assistant api` showing `ok` in the main window? Can you toggle other entities, eg. a light?

**Comment by rolandorojas** [comment]
Yes, it does show `ok` and I can run device actions like turn on and turn off a light. I only see this issue when I'm trying to run an automation or a scene. 

You can see in the logs below how I turned on a light successfully and then right after tried to run an automation and failed. 
```
2022-08-31 09:07:05.089 -04:00 [INF] [HASS_API] [light.office_lamp] Performing action: turn_on
2022-08-31 09:07:05.171 -04:00 [INF] [HASS_API] [light.office_lamp] Action completed: turn_on
2022-08-31 09:07:31.899 -04:00 [INF] [HASS_API] [automation.turn_on_off_office_tv_from_jarvis] Performing action: open_cover
2022-08-31 09:07:31.904 -04:00 [FTL] [HASS_API] [automation.turn_on_off_office_tv_from_jarvis] Error while processing action: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
```

**Comment by LAB02-Admin** [comment]
Sorry for the late reply! Completely missed your response. But I think I noticed what's wrong, you've set the `Desired action` to `Open`, which isn't applicable for automations, choose `On` instead.

I've created a ticket to change this behavior: [hassagent-146](https://github.com/LAB02-Research/HASS.Agent/issues/146)
