### ISSUE TITLE
Bug:  Local port is blocked

### ISSUE THREAD

**Issue by geiseri** [LAB02-Research/HASS.Agent#147]
**Describe the bug**
Windows wont let you listen locally even after firewall is set.

**To Reproduce**
1. Unzip the agent archive to: `%appdata%\LAB02 Research\HASS.Agent`
2. Try to enable the local listener.
3. Let it create the firewall rule
4. Restart

**Expected behavior**
Listen on the local host.

**Screenshots**
![image](https://user-images.githubusercontent.com/2265693/186252247-29572b93-6c84-4fcb-a463-db5e567b7e6d.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 -  ![image](https://user-images.githubusercontent.com/2265693/186252771-c9aa3296-6af0-4f81-b269-f02515695d73.png)

 - Windows' UI language: en_us
 - HASS.Agent version:  2022.12.0

Please check what's applicable (multiple answers possible):

 - [] Installed via installer (doesn't work due to #67)
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**

```
2022-08-23 15:55:39.043 -04:00 [INF] [MAIN] Extended logging enabled
2022-08-23 15:55:39.049 -04:00 [INF] [SETTINGS] Config storage path: C:\Users\geiseri\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-08-23 15:55:39.212 -04:00 [INF] [SETTINGS] Configuration loaded
2022-08-23 15:55:39.217 -04:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-08-23 15:55:39.590 -04:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 1 entities
2022-08-23 15:55:39.593 -04:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2022-08-23 15:55:39.618 -04:00 [INF] [SETTINGS_SENSORS] Loaded 1 entities
2022-08-23 15:55:39.626 -04:00 [INF] [LOCALAPI] Initializing ..
2022-08-23 15:55:39.627 -04:00 [INF] [MQTT] Identifying as device: IANS_DESKTOP
2022-08-23 15:55:39.627 -04:00 [INF] [NOTIFIER] Ready
2022-08-23 15:55:39.627 -04:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\HASS.Agent.Satellite.Service\
2022-08-23 15:55:39.628 -04:00 [INF] [MEDIA] Ready
2022-08-23 15:55:39.631 -04:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2022-08-23 15:55:39.644 -04:00 [INF] [MQTT] Connecting ..
2022-08-23 15:55:39.857 -04:00 [INF] [MQTT] Connected
2022-08-23 15:55:40.075 -04:00 [FTL] [PROGRAM] FirstChanceException: Access is denied.
System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
2022-08-23 15:55:40.077 -04:00 [FTL] [PROGRAM] FirstChanceException: Safe handle has been closed.
Object name: 'SafeHandle'.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Kernel32.CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped)
   at System.Net.HttpListenerSession.CloseRequestQueueHandle()
2022-08-23 15:55:40.077 -04:00 [FTL] [PROGRAM] FirstChanceException: Access is denied.
System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Grapevine.RestServer.Start()
2022-08-23 15:55:40.083 -04:00 [FTL] An unexpected error occurred when attempting to start the server
System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Grapevine.RestServer.Start()
2022-08-23 15:55:40.085 -04:00 [FTL] [PROGRAM] FirstChanceException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.CheckDisposed()
   at System.Net.HttpListener.Stop()
2022-08-23 15:55:40.085 -04:00 [FTL] [LOCALAPI] Error trying to bind the API to port 5115: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.CheckDisposed()
   at System.Net.HttpListener.Stop()
   at Grapevine.RestServer.Start()
   at Grapevine.MiddlewareExtensions.Run(IRestServer server)
   at HASS.Agent.API.ApiManager.Initialize()
2022-08-23 15:55:40.770 -04:00 [INF] [HASS_API] Home Assistant version: 2022.8.6
2022-08-23 15:55:41.661 -04:00 [INF] [MQTT] Initial registration completed
2022-08-23 15:55:41.824 -04:00 [INF] [HASS_API] System connected with http://homeassistant.local:8123
```

**Comment by LAB02-Admin** [comment]
Did you execute the port reservation:

![image](https://user-images.githubusercontent.com/81011038/186357787-16913209-1cb5-44db-9ebf-cecbf6bb27c9.png)

**Comment by geiseri** [comment]
Yes.  I did it via that button, the UI, and netsh.  The logs came as follows:

```
2022-08-24 10:10:00.671 -04:00 [INF] [SETTINGS] Config storage path: C:\Users\geiseri\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-08-24 10:10:01.414 -04:00 [INF] [SETTINGS] Configuration loaded
2022-08-24 10:10:01.448 -04:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-08-24 10:10:01.454 -04:00 [INF] [SYSTEM] Port reservation mode activated
2022-08-24 10:10:03.852 -04:00 [INF] [LOCALAPI] Executing port reservation for port: 5116
2022-08-24 10:10:04.179 -04:00 [INF] [LOCALAPI] Port reservation succesfully added
2022-08-24 10:10:04.181 -04:00 [INF] [PORTRESERVATION] Port reservation completed
2022-08-24 10:10:04.336 -04:00 [WRN] [PROCESS] Execution returned non-ok exitcode (exitcode: 1): netsh
2022-08-24 10:10:04.460 -04:00 [INF] [FIREWALL] Succesfully created firewall rule on port: 5116
2022-08-24 10:10:04.461 -04:00 [INF] [PORTRESERVATION] Firewall rule created
```

What is strange is that I see the line `2022-08-24 10:10:04.336 -04:00 [WRN] [PROCESS] Execution returned non-ok exitcode (exitcode: 1): netsh` even if its not currently present.   I am wondering if its a permissions thing here.  I did try to create the firewall rule via `netsh` as administrator, but it didn't seem to help.

**Comment by Flightkick** [comment]
@geiseri I don't think the issue originates from your firewall configuration. This seems to be a port mapping issue.
I encountered the same issue while installing the agent for an unprivileged user account.

The port reservation specifies which user is able to listen on that port number.
If you installed the agent with Admin rights, that user defaults to that admin user, hence the user that is currently running is not allowed to bind the API to that port.

To fix this:
- Open cmd with admin privileges
- Run `netsh http delete urlacl url=http://+:5115/` to remove the current existing port mapping
- Recreate the port mapping with the correct user: `netsh http add urlacl url=http://+:5115/ user=DOMAIN\user listen=yes` (replace 'DOMAIN\user' with the user account you're running the agent from).
- Restart the agent

**Comment by geiseri** [comment]
Sorry it took so long to get back to this.  I think the real issue is related to the installer itself.  It requires administrative permissions, and I (rightly so) do allow my desktop user to elevate privileges.  This has a side-effect that some installers will then ask for elevated permissions and then install the application as administrator in its root.  I will see if I can make a PR to address this.  I was going to try a zip based install to see if it faired any better.   Keep this closed for now since it seems to work for others though.  I admit I am "speshul" =)
