### ISSUE TITLE
Bug: Webview isn't at the topmost layer sometimes

### ISSUE THREAD

**Issue by brainiac19** [LAB02-Research/HASS.Agent#160]
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
Webview not showing up when right clicking tray icon.

**To Reproduce**
Havn't found anything conclusive. It happens quite a lot but not sure what's the determining variable here.

**Expected behavior**
Webview should appear when right clicking tray icon.

**Screenshots**
Not really any screenshot. The actual phenomenon of the problem is basically webview not showing up at all, only later did I find out it's there but just blocked by other windows.

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://user-images.githubusercontent.com/51896856/189247343-72861693-78d2-4a45-9a5f-4748e9f2db1f.png)

 - Windows' UI language: English
 - HASS.Agent version: 2022.13.0-beta2

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
If I go back to desktop, webview is right there. And if I click on it, it works as usual again, appearing at the topmost layer.

**Logs**
2022-09-09 07:39:52.190 +08:00 [FTL] [UPDATER] Error checking for updates: The requested name is valid, but no data of the requested type was found. (api.github.com:443)
System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found. (api.github.com:443)
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/HttpClientAdapter.cs:line 275
   at Octokit.Internal.HttpClientAdapter.Send(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/HttpClientAdapter.cs:line 78
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 690
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 675
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 74
   at HASS.Agent.Managers.UpdateManager.CheckIsUpdateAvailableAsync()

**Comment by LAB02-Admin** [comment]
Interesting, I'll look into it, thanks!

**Comment by LAB02-Admin** [comment]
Should be fixed in the latest beta if you want to test:
https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.14.0-beta1

**Comment by brainiac19** [comment]
Actually I don't think I can really test if it's fixed. Maybe it was some Windows updates that affected something, I havn't had encountered this problem for quite some time. My apologies.

**Comment by LAB02-Admin** [comment]
No worries :)
