### ISSUE TITLE
Bug: JsonException: The input does not contain any JSON tokens.

### ISSUE THREAD

**Issue by petarvucetin** [LAB02-Research/HASS.Agent#172]
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
Notifications are not showing up

**To Reproduce**
New installation 

**Expected behavior**
Notification popup not showing

**Screenshots**
N/A

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 21H2 build 19044.2006
 - Windows' UI language: EN
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
2022-09-23 14:18:56.351 -07:00 [INF] [HASS_API] Home Assistant version: 2022.9.4
2022-09-23 14:18:56.479 -07:00 [INF] [LOCALAPI] listening on port 5115
2022-09-23 14:18:56.565 -07:00 [INF] [HASS_API] System connected with http://192.168.1.61:8123
2022-09-23 14:18:58.324 -07:00 [INF] [MQTT] Initial registration completed
2022-09-23 17:35:03.461 -07:00 [INF] [NOTIFIER] Attempting to show test notification ..
2022-09-23 17:35:03.478 -07:00 [INF] [NOTIFIER] Test notification attempt completed
2022-09-23 17:35:55.445 -07:00 [INF] [NOTIFIER] Attempting to show test notification ..
2022-09-23 17:35:55.453 -07:00 [INF] [NOTIFIER] Test notification attempt completed
2022-09-23 17:39:09.069 -07:00 [FTL] [LOCALAPI] Error while processing incoming notification: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at HASS.Agent.API.ApiDeserialization.DeserializeAsync[T](Stream stream, CancellationToken token)
   at HASS.Agent.API.ApiEndpoints.NotifyRoute(IHttpContext context)
2022-09-23 17:40:05.445 -07:00 [INF] [NOTIFIER] Attempting to show test notification ..
2022-09-23 17:40:05.452 -07:00 [INF] [NOTIFIER] Test notification attempt completed
2022-09-23 18:31:49.257 -07:00 [INF] [SYSTEM] Application shutting down
2022-09-23 18:31:49.260 -07:00 [INF] [MQTT] Disconnected
2022-09-23 18:31:49.267 -07:00 [INF] [SYSTEM] Application shutdown complete

**Comment by LAB02-Admin** [comment]
What version of HASS.Agent are you using, and what version of the integration? Did you follow the examples:

https://hassagent.readthedocs.io/en/latest/notifications/notification-usage-and-examples/

**Comment by petarvucetin** [comment]
HASS Agent - 2022.12.0

HASS.Agent Notifier2022.3.15

 

I checked firewall (disabled on server and client)

Checked that I can ping {device_ip} referenced in the config

Checked port 5515 is running on my machine (netstat)

**Comment by petarvucetin** [comment]
Content is simple message “Test”

 

2022-10-11 08:53:35.415 -07:00 [INF] [MEDIA] New state: Paused

2022-10-11 08:53:35.569 -07:00 [INF] [HASS_API] System connected with http://192.168.1.61:8123

2022-10-11 08:53:36.119 -07:00 [INF] [LOCALAPI] listening on port 5115

2022-10-11 08:53:37.262 -07:00 [INF] [MQTT] Initial registration completed

2022-10-11 08:53:50.637 -07:00 [INF] [NOTIFIER] Attempting to show test notification ..

2022-10-11 08:53:50.736 -07:00 [INF] [NOTIFIER] Test notification attempt completed

 

But notification never shows. I have tried running the app as admin with same results.

 

Hass config:

notify: 

  name: "hass agent on petar"

  platform: hass_agent_notifier

  resource: http://192.168.1.175:5115/notify

**Comment by petarvucetin** [comment]
It was windows alerts that were disabled. Thank you for great app!
