### ISSUE TITLE
Bug: Satellite Service Network Sensor does not detect NICs

### ISSUE THREAD

**Issue by tarrychk** [LAB02-Research/HASS.Agent#179]
**Describe the bug**
Network sensor does not detect network cards nor sends any metrics when configured in Satellite Service.
Only metric that gets generated is "Network Card Count": 0.

It works fine when configured in HASS.Agent.

**To Reproduce**
- manage satellite service
- add "Network" Sensor
- store sensor
- check Home Assistant Entities for satellite service metrics

**Expected behavior**
Satellite service should generate the same set of network metrics that HASS.Agent generates.

**Misc info (please complete the following information):**
![image](https://user-images.githubusercontent.com/11613638/194842883-a43a96c7-df3b-4032-a453-2cbd18fe5f1a.png)
 - Windows' UI language: German
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Comment by tarrychk** [comment]
Satellite Service Logs:
```
2022-10-10 12:59:37.014 +02:00 [INF] [MAIN] Version: 2022.13.0.0
2022-10-10 12:59:37.085 +02:00 [INF] [MAIN] Service started, initializing ..
2022-10-10 12:59:37.455 +02:00 [INF] [MAIN] Running as a service, initializing lifetime manager
2022-10-10 12:59:37.557 +02:00 [INF] [LIFETIMEMANAGER] Initialized
2022-10-10 12:59:37.632 +02:00 [INF] [WORKER] Startup completed, commencing execution ..
2022-10-10 12:59:37.636 +02:00 [INF] [SETTINGS] Config storage path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\config
2022-10-10 12:59:37.997 +02:00 [INF] [SETTINGS] Configuration loaded
2022-10-10 12:59:38.010 +02:00 [INF] [SETTINGS] MQTT configuration loaded
2022-10-10 12:59:38.046 +02:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-10-10 12:59:38.101 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 1 entities
2022-10-10 13:00:09.375 +02:00 [INF] [LIFETIMEMANAGER] SessionChange: ConsoleConnect
2022-10-10 13:00:10.042 +02:00 [INF] [LIFETIMEMANAGER] SessionChange: SessionLogon
2022-10-10 13:00:13.176 +02:00 [INF] [LIFETIMEMANAGER] SessionChange: SessionLock
2022-10-10 13:00:13.373 +02:00 [FTL] [WUPDATE] Unable to query update status, Windows update seems to be corrupt: 0x80248014
System.Runtime.InteropServices.COMException (0x80248014): 0x80248014
   at WUApiLib.IUpdateSearcher.Search(String criteria)
   at HASS.Agent.Shared.Functions.WindowsUpdatesManager.GetUpdateList()
2022-10-10 13:00:13.837 +02:00 [INF] [SETTINGS_SENSORS] Loaded 3 entities
2022-10-10 13:00:14.303 +02:00 [INF] [MQTT] Identifying as device: XXXXXX-satellite
2022-10-10 13:00:14.701 +02:00 [INF] [MQTT] Connecting ..
2022-10-10 13:00:14.827 +02:00 [INF] [RPCMANAGER] Listening
2022-10-10 13:00:15.236 +02:00 [INF] [MQTT] Connected
2022-10-10 13:00:16.731 +02:00 [INF] [MQTT] Initial registration completed
2022-10-10 13:00:20.776 +02:00 [INF] [LIFETIMEMANAGER] SessionChange: SessionUnlock
```

Agent Logs:
```
2022-10-10 13:01:12.818 +02:00 [INF] [SETTINGS] Config storage path: C:\Users\tarry\AppData\Roaming\LAB02 Research\HASS.Agent\config
2022-10-10 13:01:13.279 +02:00 [INF] [SETTINGS] Configuration loaded
2022-10-10 13:01:13.295 +02:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-10-10 13:01:14.368 +02:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2022-10-10 13:01:14.375 +02:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2022-10-10 13:01:14.799 +02:00 [INF] [SETTINGS_SENSORS] Loaded 2 entities
2022-10-10 13:01:14.817 +02:00 [INF] [NOTIFIER] Ready
2022-10-10 13:01:14.823 +02:00 [INF] [MEDIA] Ready
2022-10-10 13:01:14.828 +02:00 [INF] [MQTT] Identifying as device: XXXXXX
2022-10-10 13:01:14.834 +02:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-10-10 13:01:14.849 +02:00 [INF] [LOCALAPI] Initializing ..
2022-10-10 13:01:14.861 +02:00 [INF] [MQTT] Connecting ..
2022-10-10 13:01:15.166 +02:00 [INF] [HASS_API] Home Assistant version: 2022.10.0
2022-10-10 13:01:15.226 +02:00 [INF] [MQTT] Connected
2022-10-10 13:01:15.754 +02:00 [INF] [HASS_API] System connected with http://xxxxxx:8123
2022-10-10 13:01:16.550 +02:00 [INF] [LOCALAPI] listening on port 5115
2022-10-10 13:01:16.894 +02:00 [INF] [MQTT] Initial registration completed
```

**Comment by LAB02-Admin** [comment]
Could you please try this beta: https://github.com/LAB02-Research/HASS.Agent/releases/download/2022.13.0-beta1/HASS.Agent.Installer.exe

There was a bug storing the sensor in the satellite service

**Comment by tarrychk** [comment]
2022.13.0-beta1 fixes the issue.
