### ISSUE TITLE
Bug: HASS.Agent satellite service queries homeassistant.local although a static IP is set in config

### ISSUE THREAD

**Issue by thecode** [LAB02-Research/HASS.Agent#186]
**Describe the bug**
Similar to https://github.com/LAB02-Research/HASS.Agent/issues/61, I am using a static IP for the MQTT server, my Home Assistant instance is not using the default value `homeassistant.local` as a hostname, this causes the satellite service to try to resolve a non-existing hostname and fail (see logs bellow and screenshot bellow). 

HASS.Agent MQTT is working correctly, it is just the satellite service which ignore the settings, the IP in the picture is not found in the service logs.

**NOTE:**
Just before submitting the issue I have checked to see if there is any local config file for the satelite service and found the following in `servicemqttsettings.json`, the username and password there also doesn't match the ones set in the UI. I have even tried to delete this file and reinstall the service it, it will get the default values.
```json
{
  "MqttAddress": "homeassistant.local",
  "MqttPort": 1883,
  "MqttUseTls": false,
  "MqttAllowUntrustedCertificates": true,
  "MqttUsername": "",
  "MqttPassword": "",
  "MqttDiscoveryPrefix": "homeassistant",
  "MqttClientId": "fcfb5f53",
  "MqttUseRetainFlag": true,
  "MqttRootCertificate": "",
  "MqttClientCertificate": ""
}
```

**To Reproduce**
1. Set a static IP for the MQTT server
2. Check the satellite service logs for errors

**Expected behavior**
Satellite service should use the IP set in the MQTT configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/1858925/195908197-5bc682fd-c6d1-4e29-971c-60ef61d18c39.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://user-images.githubusercontent.com/1858925/195908963-8602267e-67d5-44bc-a7f2-f2b0cb311df2.png)

 - Windows' UI language: English
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

```
2022-10-14 10:15:48.609 +03:00 [FTL] [MQTT] Error while connecting: Error while connecting with host 'homeassistant.local:1883'.
MQTTnet.Exceptions.MqttCommunicationException: Error while connecting with host 'homeassistant.local:1883'.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync(CancellationToken cancellationToken)
2022-10-14 10:20:16.778 +03:00 [INF] [SYSTEMSTATE] Session halting: system suspending
```

**Comment by LAB02-Admin** [comment]
Hi @thecode,

The satellite service has its own config:

![image](https://user-images.githubusercontent.com/81011038/196959955-69c79d93-6f27-436d-ae36-1e22f9416fac.png)

You can get to this screen by clicking on the `satellite service` button in the main window.

In the upcoming version, when you change mqtt for hass.agent, it gets propagated to the satellite service. That would fix this issue right? Or am I missing something?
