### ISSUE TITLE
Constant "[WRN] [MEDIA] Null object received when requesting CurrentMediaSession" in log, media player not working.

### ISSUE THREAD

**Issue by ruipin** [LAB02-Research/HASS.Agent#187]
I do not seem to be able to get the media player integration working in 2022.12.0 and 2022-13.0-beta4. This is essentially on a fresh install.

Enabling the local API works, as do notifications. However, the media player integration is unable to connect with the error:
```
2022-10-14 19:23:29.040 DEBUG (SyncWorker_9) [custom_components.hass_agent_mediaplayer.media_player] Could not connect to HASS.Agent MediaPlayer at: http://192.168.x.x:5115/media
```

If I wget from the HASS device to `http://192.168.x.x:5115` I get `HASS.Agent Active` as expected.
However, `http://192.168.x.x:5115/media` (from the error message) gives me `Method Not Implemented: Get /media`.

Looking at the logs (with extended logs enabled), I see the following messages:

````
2022-10-14 19:39:24.028 +01:00 [INF] [MAIN] Extended logging enabled
2022-10-14 19:39:24.032 +01:00 [INF] [SETTINGS] Config storage path: D:\Program Files\HASS.Agent\config
2022-10-14 19:39:24.120 +01:00 [INF] [SETTINGS] Configuration loaded
2022-10-14 19:39:24.123 +01:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2022-10-14 19:39:24.367 +01:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 0 entities
2022-10-14 19:39:24.386 +01:00 [INF] [SETTINGS_COMMANDS] Loaded 6 entities
2022-10-14 19:39:24.509 +01:00 [FTL] [PROGRAM] FirstChanceException: Element not found. (0x80070490)
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at CoreAudio.AudioSessionManager2.UnregisterNotifications()
2022-10-14 19:39:24.565 +01:00 [INF] [SETTINGS_SENSORS] Loaded 1 entities
2022-10-14 19:39:24.569 +01:00 [INF] [LOCALAPI] Initializing ..
2022-10-14 19:39:24.569 +01:00 [INF] [MQTT] Identifying as device: Desktop
2022-10-14 19:39:24.569 +01:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-10-14 19:39:24.574 +01:00 [INF] [MQTT] Connecting ..
2022-10-14 19:39:24.655 +01:00 [INF] [NOTIFIER] Ready
2022-10-14 19:39:24.656 +01:00 [INF] [MQTT] Connected
2022-10-14 19:39:24.658 +01:00 [INF] [HASS_API] Home Assistant version: 2022.10.3
2022-10-14 19:39:24.672 +01:00 [INF] [MEDIA] Ready
2022-10-14 19:39:24.683 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:24.766 +01:00 [INF] [HASS_API] System connected with https://<omitted for privacy>
2022-10-14 19:39:24.815 +01:00 [INF] [LOCALAPI] listening on port 5115
2022-10-14 19:39:26.581 +01:00 [INF] [MQTT] Initial registration completed
2022-10-14 19:39:26.706 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:28.726 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:30.749 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:32.757 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:34.769 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:36.780 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:38.786 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:40.812 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:42.818 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:44.844 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:46.360 +01:00 [FTL] [PROGRAM] FirstChanceException: Element not found. (0x80070490)
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at CoreAudio.AudioSessionManager2.UnregisterNotifications()
2022-10-14 19:39:46.853 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:48.873 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
2022-10-14 19:39:50.880 +01:00 [WRN] [MEDIA] Null object received when requesting CurrentMediaSession
...
````

The constant spam of that last message continues basically forever, as long as HASS.Agent is running with the media player extension enabled. The other `[FTL] [PROGRAM]` message shows up every few minutes or so.

I tried searching through the source code for the location of this warning, but couldn't for the life of me find it, unfortunately. Every single `[MEDIA]` warning I found would have a different message prefixing an error. `CurrentMediaSession` also doesn't seem to show up.

Also worth noting something does get published to `hass.agent/media_player/Desktop/state` (but no device is auto-detected by the MQTT integration):

````
{"duration":0,"currentposition":0,"state":"Off","volume":0,"muted":false}
````

Normal media keys work, as does mapping commands to the media keys in HASS.Agent, so I don't think it is a problem of the music players I have tested with.

Any ideas for a solution appreciated.

**Misc info (please complete the following information):**
 - Windows build: Version 21H1 (OS Build 19043.2130)
 - Windows' UI language: English UK
 - HASS.Agent version: 2022.12.0 and 2022.13.0-beta4

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by ruipin** [comment]
Okay, seems this warning is due to an incompatible media player.
I was using MusicBee, but running Media Player Classic makes the warning go away. I guess it simply means that MusicBee is not supported by this app (even though Windows detects it as a music player), and I guess I'll have to rely on the media keys instead.

Sorry for the spam, closing.
