### ISSUE TITLE
Bug: All entities marked as unavailable after booting from hibernation

### ISSUE THREAD

**Issue by ScottG489** [LAB02-Research/HASS.Agent#195]
**Describe the bug**
Entities are all marked as unavailable and don't update after booting up from a hibernated state.

In the past I've gotten things to be back to normal by going into the sensors config and clicking "store and activate sensors". However, I just tried now and that didn't work. Restarting HASS.Agent was the only thing that got the entities back not being available.

One thing to note, though, is that it doesn't happen consistently. Sometimes it works fine, but it's maybe 50/50.

**To Reproduce**
1. Hibernate the computer while HASS.Agent is running and operating fine
2. Start the computer

**Expected behavior**
For all of the entities to be available without manual intervention.

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): **Windows 10 - Version 21H1 (OS build 19043.2130)**
 - Windows' UI language: ?
 - HASS.Agent version: **2022.12.0**

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
HASS.Agent:
```
2022-10-23 01:14:59.445 -04:00 [INF] [HASS_API] Server recovered from failed state
2022-10-23 01:23:03.825 -04:00 [INF] [SYSTEMSTATE] Session halting: system suspending
2022-10-23 12:33:29.172 -04:00 [INF] [SYSTEMSTATE] Session resuming
2022-10-23 12:34:26.700 -04:00 [INF] [MQTT] Connected
2022-10-23 12:34:27.014 -04:00 [INF] [MQTT] Connected
2022-10-23 12:34:44.785 -04:00 [FTL] [HASS_API] Error while fetching HA config: An error occurred while sending the request.
2022-10-23 12:35:08.513 -04:00 [INF] [HASS_API] Server recovered from failed state
```
HASS.Agent.Satelite.Service:
```
2022-10-23 01:22:59.793 -04:00 [INF] [SYSTEMSTATE] Session halting: system suspending
2022-10-23 12:33:29.155 -04:00 [INF] [SYSTEMSTATE] Session resuming
```

**Comment by ScottG489** [comment]
I enabled extended logging. Here are the logs below after the incident occurred again. I noticed at least this time the entities became available initially after booting from hibernate and then became unavailable shortly after.
```
2022-10-24 00:15:55.688 -04:00 [INF] [SYSTEMSTATE] Session halting: system suspending
2022-10-24 19:26:51.048 -04:00 [INF] [SYSTEMSTATE] Session resuming
2022-10-24 19:26:51.176 -04:00 [FTL] [PROGRAM] FirstChanceException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
2022-10-24 19:26:51.176 -04:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
2022-10-24 19:26:51.176 -04:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-10-24 19:26:51.176 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.177 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.540 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.540 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.541 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.541 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.541 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.541 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.541 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.541 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An established connection was aborted by the software in your host machine.
2022-10-24 19:26:51.541 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.542 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.542 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.542 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An established connection was aborted by the software in your host machine.
2022-10-24 19:26:51.542 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.542 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.545 -04:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.AsyncQueue`1.TryDequeueAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.783 -04:00 [ERR] [NET] [FirstChanceHttpRequestException.SocketException] An error occurred while sending the request.
2022-10-24 19:26:51.921 -04:00 [FTL] [PROGRAM] FirstChanceException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.ContinueWithTaskContinuation.Run(Task completedTask, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.Task.CancellationPromise`1.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.CompletionActionInvoker.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
2022-10-24 19:26:51.921 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.921 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.922 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.922 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.922 -04:00 [FTL] [NET] FirstChancemqttCommunicationException: The TCP connection is closed.
MQTTnet.Exceptions.MqttCommunicationException: The TCP connection is closed.
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.PublishAtMostOnce(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.TryPublishQueuedMessageAsync(ManagedMqttApplicationMessage message)
2022-10-24 19:26:51.922 -04:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.922 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2022-10-24 19:26:51.922 -04:00 [FTL] [NET] FirstChancemqttCommunicationException: The TCP connection is closed.
MQTTnet.Exceptions.MqttCommunicationException: The TCP connection is closed.
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.PublishAtMostOnce(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.TryPublishQueuedMessageAsync(ManagedMqttApplicationMessage message)
2022-10-24 19:26:51.923 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:51.923 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An established connection was aborted by the software in your host machine.
2022-10-24 19:26:52.107 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:52.109 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An established connection was aborted by the software in your host machine.
2022-10-24 19:26:52.110 -04:00 [FTL] [NET] [ConnectionAborted] An established connection was aborted by the software in your host machine.
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReadFixedHeaderAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
2022-10-24 19:26:52.110 -04:00 [ERR] [NET] [MqttCommunicationException.SocketException] An established connection was aborted by the software in your host machine.
2022-10-24 19:26:52.177 -04:00 [FTL] [NET] [HostUnreachable] A socket operation was attempted to an unreachable host.
System.Net.Sockets.SocketException (10065): A socket operation was attempted to an unreachable host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2022-10-24 19:26:53.587 -04:00 [ERR] [NET] [FirstChanceHttpRequestException.SocketException] An error occurred while sending the request.
2022-10-24 19:26:53.588 -04:00 [ERR] [NET] [FirstChanceHttpRequestException.SocketException] An error occurred while sending the request.
2022-10-24 19:26:53.590 -04:00 [ERR] [NET] [FirstChanceHttpRequestException.SocketException] An error occurred while sending the request.
2022-10-24 19:26:57.457 -04:00 [FTL] [NET] [HostUnreachable] A socket operation was attempted to an unreachable host.
System.Net.Sockets.SocketException (10065): A socket operation was attempted to an unreachable host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
2022-10-24 19:26:59.130 -04:00 [FTL] [HASS_API] Error while fetching HA config: An error occurred while sending the request.
2022-10-24 19:27:02.170 -04:00 [INF] [HASS_API] Server recovered from failed state
2022-10-24 19:27:02.407 -04:00 [WRN] [MQTT] Not connected, message dropped (won't report again for 5 minutes)
2022-10-24 19:27:02.497 -04:00 [INF] [MQTT] Connected
2022-10-24 19:27:26.202 -04:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessagesAsync(CancellationToken cancellationToken)
2022-10-24 19:27:26.203 -04:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
2022-10-24 19:27:26.705 -04:00 [INF] [MQTT] Connected
2022-10-24 19:29:47.306 -04:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)

```
I should also mention that I have quite a few other devices using MQTT just fine (Zigbee2MQTT, Tasmota, etc).

**Comment by ScottG489** [comment]
Just wanted to mention that I updated to the most recent release and this issue is still present.

**Comment by LAB02-Admin** [comment]
Yep aware of the problem, related to #136. 

However, in your case, it seems that HASS.Agent has trouble connecting. Any idea why that is, perhaps a slow network connection? Does it recover after a while?

**Comment by ScottG489** [comment]
My network is pretty fast and reliable and I don't have other issues like that so I don't think that would be the case.

I'm not 100% certain, but I'm pretty sure it doesn't ever recover without manual intervention on the physical machine. However, it also isn't something that happens every time and will sometimes reconnected after booting from hibernate.

Also related to that issue you linked, I just noticed that it did in fact not reconnect after HA was restarted.

Another issue I'm having which isn't related (I had these hibernate issues before) but I thought I'd mention is with the new integration. It has no entities associated with it. Perhaps I didn't do the setup properly, but I was already using MQTT and had my entities in place. Now with the integration there are no entities associated with the device.

<img width="266" alt="Screen Shot 2022-10-28 at 1 00 59 AM" src="https://user-images.githubusercontent.com/910809/198506583-cc863a14-498c-4333-91d2-574242bd3942.png">

The old entities are still there and working fine. Just the new device from the integration doesn't have anything. Happy to create a new issues for this if you'd like.

**Comment by LAB02-Admin** [comment]
That's corect, there are two devices: one for hass.agent, one for the integrations. They're not linked within HA, that would be a bit difficult to keep synced.

**Comment by LAB02-Admin** [comment]
I've merged all tickets related to this issue into a central pinned one: [#204]

Closing this one to keep it in one place.

**Comment by ScottG489** [comment]
Great, thanks for looking into this!

Regarding the two devices, what is the purpose of the integration device? For me it's completely empty. It isn't necessarily a problem, but I want to make sure I'm not missing something because I'm failing to see the purpose of the integration or what benefit it provides.

**Comment by LAB02-Admin** [comment]
Could it be that you don't have mediaplayer enabled? There are two services connected to the integration; the media_player and notify. The media_player shows up as an entity, but the notify is only a service - so it doesn't show up at all (unless called of course).

**Comment by ScottG489** [comment]
That's correct. I'm not currently using the media_player or notify service. So it sounds like that's why. Will keep an eye out if I enable those in the future!
