### ISSUE TITLE
Bug: Quick actions not working but commands works in python script

### ISSUE THREAD

**Issue by icegothic** [LAB02-Research/HASS.Agent#231]
Hi, 

I'm trying to control my TV using Hass Agent's quick actions but it's not working... However it works perfectly using a web call in a python script. Should'nt Hass Agent work as well !?

Here's my QuickActions config:
![image](https://user-images.githubusercontent.com/16883752/206910003-ae8bd980-5144-4d0b-8ac8-0d0e6c1759e9.png)
![image](https://user-images.githubusercontent.com/16883752/206910494-65380c30-40bc-4830-b944-90161da440a3.png)

**Note**: the turn_on action did not turn on the tv and the "Error while processing action" occurs when I try the turn_off action.

Here the python script that works: 
```
from requests import post

url = "http://assistant:8123/api/services/media_player/turn_off"
headers = {
    "Authorization": "Bearer {token}",
    "content-type": "application/json",
}

data = {"entity_id": "media_player.tv"}
post(url, headers=headers, json=data)
```

I'm using Windows 11 (END) with HASS.Agent version 2022.14.0.

 - Windows build (ideally screenshot/info of `winver.exe` output): 
 - Windows' UI language: 
 - HASS.Agent version: 

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [don't know] Problem occurs in Satellite Service

**Logs**
```
2022-12-11 09:32:15.410 -05:00 [INF] [HASS_API] [media_player.tv] Performing action: turn_on
2022-12-11 09:32:20.417 -05:00 [INF] [HASS_API] [media_player.tv] Action completed: turn_on
2022-12-11 09:32:45.323 -05:00 [INF] [HASS_API] [media_player.tv] Performing action: turn_off
2022-12-11 09:32:45.330 -05:00 [FTL] [HASS_API] [media_player.tv] Error while processing action: Response status code does not indicate success: 500 (Internal Server Error).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
```

**Comment by LAB02-Admin** [comment]
Sorry for the late reply, been really busy.

Yep, odd. I'm completely rewriting the quickactions code for fetching services/actions/etc, so please sit tight and see if it's fixed with the coming release :)
