### ISSUE TITLE
Error doing job: Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by Anto79-ops** [LAB02-Research/HASS.Agent#270]
Hi,

I had to enable to debugpy in HA to get more details on this error message I've been receiving since updating to 2023.2.x (HAOS).

Running HassAgent on Windows 10 and its the latest version.

```
2023-02-06 12:45:23.028 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in updated when handling msg on 'hass.agent/devices/ANTONIO_HP': '{"serial_number":"REDACTED","device":{"identifiers":"hass.agent-ANTO_HP","manufacturer":"LAB02 Research","model":"Microsoft Windows NT 10.0.19045.0","name":"ANTO_HP","sw_version":"2022.14.0"},"apis":{"notifications":true,"media_player":true}}'
Traceback (most recent call last):
  File "/config/custom_components/hass_agent/__init__.py", line 147, in updated
    hass.async_create_task(handle_apis_changed(hass, entry, apis))
  File "/usr/src/homeassistant/homeassistant/core.py", line 518, in async_create_task
    task = self.loop.create_task(target)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

2023-02-06 12:45:23.030 ERROR (SyncWorker_6) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 169, in wrapper
    func(*args)
  File "/config/custom_components/hass_agent/__init__.py", line 147, in updated
    hass.async_create_task(handle_apis_changed(hass, entry, apis))
  File "/usr/src/homeassistant/homeassistant/core.py", line 518, in async_create_task
    task = self.loop.create_task(target)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task
    task = tasks.Task(coro, loop=self, name=name)
```

**Comment by Anto79-ops** [comment]
Wanted to reference a comment here in hopes of shedding more light on the nature of the log errors. Thanks 

https://github.com/home-assistant/core/issues/87230#issuecomment-1425162015

**Comment by bdraco** [comment]
```diff
diff --git a/custom_components/hass_agent/__init__.py b/custom_components/hass_agent/__init__.py
index 73f81c8..73d1042 100644
--- a/custom_components/hass_agent/__init__.py
+++ b/custom_components/hass_agent/__init__.py
@@ -11,10 +11,11 @@ from homeassistant.components.mqtt.subscription import (
     async_subscribe_topics,
     async_unsubscribe_topics,
 )
+from homeassistant.util.json import json_loads
 
 from homeassistant.config_entries import ConfigEntry
 from homeassistant.const import CONF_ID, CONF_NAME, CONF_URL, Platform
-from homeassistant.core import HomeAssistant
+from homeassistant.core import HomeAssistant, callback
 from homeassistant.helpers import discovery
 
 from .const import DOMAIN
@@ -128,7 +129,7 @@ async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
             "media_player": False,  # unsupported for the moment
         }
 
-        hass.async_create_task(handle_apis_changed(hass, entry, apis))
+        hass.async_create_background_task(handle_apis_changed(hass, entry, apis))
         hass.data[DOMAIN][entry.entry_id]["apis"] = apis
 
     else:
@@ -136,15 +137,16 @@ async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
 
         sub_state = hass.data[DOMAIN][entry.entry_id]["internal_mqtt"]
 
+        @callback
         def updated(message: ReceiveMessage):
-            payload = json.loads(message.payload)
+            payload = json_loads(message.payload)
             cached = hass.data[DOMAIN][entry.entry_id]["apis"]
             apis = payload["apis"]
 
             update_device_info(hass, entry, payload)
 
             if cached != apis:
-                hass.async_create_task(handle_apis_changed(hass, entry, apis))
+                hass.async_create_background_task(handle_apis_changed(hass, entry, apis))
                 hass.data[DOMAIN][entry.entry_id]["apis"] = apis
 
         sub_state = async_prepare_subscribe_topics(
```

I have no way to test it but something like this should fix it

**Comment by Anto79-ops** [comment]
another reference here with regards to ` Non-thread-safe operation`

https://github.com/home-assistant/core/issues/91467#issuecomment-1513492482

**Comment by Anto79-ops** [comment]
I manually implement the code as above [here ](https://github.com/LAB02-Research/HASS.Agent/issues/270#issuecomment-1493590956) and wanted to add to the above, another line to change if you are implementing the suggested code change 

```
            if cached != apis:
                hass.async_create_background_task(handle_apis_changed(hass, entry, apis)**,"name"**)
                hass.data[DOMAIN][entry.entry_id]["apis"] = apis
```
all is working well now

thank you again, @bdraco

**Comment by Anto79-ops** [comment]
```
"""The HASS.Agent integration."""
from __future__ import annotations
import json
import logging
import requests
from .views import MediaPlayerThumbnailView
from homeassistant.helpers import device_registry as dr
from homeassistant.components.mqtt.models import ReceiveMessage
from homeassistant.components.mqtt.subscription import (
    async_prepare_subscribe_topics,
    async_subscribe_topics,
    async_unsubscribe_topics,
)
from homeassistant.util.json import json_loads

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_ID, CONF_NAME, CONF_URL, Platform
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import discovery

from .const import DOMAIN

PLATFORMS: list[Platform] = [Platform.MEDIA_PLAYER]

_logger = logging.getLogger(__name__)


def update_device_info(hass: HomeAssistant, entry: ConfigEntry, new_device_info):
    device_registry = dr.async_get(hass)
    device_registry.async_get_or_create(
        config_entry_id=entry.entry_id,
        identifiers={(DOMAIN, entry.unique_id)},
        name=new_device_info["device"]["name"],
        manufacturer=new_device_info["device"]["manufacturer"],
        model=new_device_info["device"]["model"],
        sw_version=new_device_info["device"]["sw_version"],
    )


async def handle_apis_changed(hass: HomeAssistant, entry: ConfigEntry, apis):
    if apis is not None:

        device_registry = dr.async_get(hass)
        device = device_registry.async_get_device(
            identifiers={(DOMAIN, entry.unique_id)}
        )

        media_player = apis.get("media_player", False)
        is_media_player_loaded = hass.data[DOMAIN][entry.entry_id]["loaded"][
            "media_player"
        ]

        notifications = apis.get("notifications", False)

        is_notifications_loaded = hass.data[DOMAIN][entry.entry_id]["loaded"][
            "notifications"
        ]

        if media_player and is_media_player_loaded is False:
            _logger.debug("loading media_player for device: %s", device.name)
            await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

            hass.data[DOMAIN][entry.entry_id]["loaded"]["media_player"] = True
        else:
            if is_media_player_loaded:
                _logger.debug(
                    "unloading media_player for device: %s",
                    device.name,
                )
                await hass.config_entries.async_forward_entry_unload(
                    entry, Platform.MEDIA_PLAYER
                )

                hass.data[DOMAIN][entry.entry_id]["loaded"]["media_player"] = False

        if notifications and is_notifications_loaded is False:
            _logger.debug("loading notify for device: %s", device.name)

            hass.async_create_task(
                discovery.async_load_platform(
                    hass,
                    Platform.NOTIFY,
                    DOMAIN,
                    {CONF_ID: entry.entry_id, CONF_NAME: device.name},
                    {},
                )
            )
            hass.data[DOMAIN][entry.entry_id]["loaded"]["notifications"] = True
        else:
            if is_notifications_loaded:
                _logger.debug("unloading notify for device: %s", device.name)
                await hass.config_entries.async_unload_platforms(
                    entry, [Platform.NOTIFY]
                )

                hass.data[DOMAIN][entry.entry_id]["loaded"]["notifications"] = False


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up HASS.Agent from a config entry."""

    hass.data.setdefault(DOMAIN, {})

    hass.data[DOMAIN].setdefault(
        entry.entry_id,
        {
            "internal_mqtt": {},
            "apis": {},
            "thumbnail": None,
            "loaded": {"media_player": False, "notifications": False},
        },
    )

    url = entry.data.get(CONF_URL, None)

    if url is not None:

        def get_device_info():
            return requests.get(f"{url}/info", timeout=10)

        response = await hass.async_add_executor_job(get_device_info)

        response_json = response.json()

        update_device_info(hass, entry, response_json)

        apis = {
            "notifications": True,
            "media_player": False,  # unsupported for the moment
        }

        hass.async_create_background_task(handle_apis_changed(hass, entry, apis))
        hass.data[DOMAIN][entry.entry_id]["apis"] = apis

    else:
        device_name = entry.data["device"]["name"]

        sub_state = hass.data[DOMAIN][entry.entry_id]["internal_mqtt"]

        @callback
        def updated(message: ReceiveMessage):
            payload = json_loads(message.payload)
            cached = hass.data[DOMAIN][entry.entry_id]["apis"]
            apis = payload["apis"]

            update_device_info(hass, entry, payload)

            if cached != apis:
                hass.async_create_background_task(handle_apis_changed(hass, entry, apis),"name")
                hass.data[DOMAIN][entry.entry_id]["apis"] = apis

        sub_state = async_prepare_subscribe_topics(
            hass,
            sub_state,
            {
                f"{entry.unique_id}-apis": {
                    "topic": f"hass.agent/devices/{device_name}",
                    "msg_callback": updated,
                    "qos": 0,
                }
            },
        )

        await async_subscribe_topics(hass, sub_state)

        hass.data[DOMAIN][entry.entry_id]["internal_mqtt"] = sub_state

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""

    # known issue: notify does not always unload

    loaded = hass.data[DOMAIN][entry.entry_id].get("loaded", None)

    if loaded is not None:
        notifications = loaded.get("notifications", False)

        media_player = loaded.get("media_player", False)

        if notifications:
            if unload_ok := await hass.config_entries.async_unload_platforms(
                entry, [Platform.NOTIFY]
            ):
                _logger.debug("unloaded %s for %s", "notify", entry.unique_id)

        if media_player:
            if unload_ok := await hass.config_entries.async_unload_platforms(
                entry, [Platform.MEDIA_PLAYER]
            ):
                _logger.debug("unloaded %s for %s", "media_player", entry.unique_id)
    else:
        _logger.warning("config entry (%s) with has no apis loaded?", entry.entry_id)

    url = entry.data.get(CONF_URL, None)
    if url is None:
        async_unsubscribe_topics(
            hass, hass.data[DOMAIN][entry.entry_id]["internal_mqtt"]
        )

    hass.data[DOMAIN].pop(entry.entry_id)

    return unload_ok


async def async_setup(hass: HomeAssistant, config) -> bool:
    hass.http.register_view(MediaPlayerThumbnailView(hass))
    return True
```

**Comment by Metus88** [comment]
Thanks a lot! I copied it inside "/homeassistant/custom_components/hass_agent/__init__.py" and now the error seems to have disappeared.
I happy to know that it will implement in the official hacs integration.
Well done and thanks again!
