### ISSUE TITLE
Bug:  Home Assistant won't detect HASS Agent devices: `FirstChanceException` and `FirstChanceHttpRequestException`

### ISSUE THREAD

**Issue by aristizabal95** [LAB02-Research/HASS.Agent#293]
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
HASS Agent has been working fine for me up until a few days ago. For some reason, the devices and commands exposed by HASS Agent are not being recognized by Home Assistant. I'm not sure what changed that caused this issue, but no matter what I try I can't get it to work.

Looking at the logs, I see a bunch of the following errors:
```
2023-03-14 09:53:11.236 -05:00 [INF] [SYSTEM] Application shutting down
2023-03-14 09:53:11.238 -05:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessagesAsync(CancellationToken cancellationToken)
2023-03-14 09:53:11.239 -05:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at MQTTnet.Implementations.MqttTcpChannel.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2023-03-14 09:53:11.244 -05:00 [INF] [MQTT] Disconnected
2023-03-14 09:53:11.292 -05:00 [FTL] [PROGRAM] FirstChanceException: Safe handle has been closed.
Object name: 'SafeHandle'.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Kernel32.CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped)
   at System.Net.HttpListenerSession.CloseRequestQueueHandle()
2023-03-14 09:53:11.293 -05:00 [FTL] [PROGRAM] FirstChanceException: The I/O operation has been aborted because of either a thread exit or an application request.
System.Net.HttpListenerException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
2023-03-14 09:53:11.293 -05:00 [FTL] [PROGRAM] FirstChanceException: The I/O operation has been aborted because of either a thread exit or an application request.
System.Net.HttpListenerException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at System.Net.HttpListener.<>c.<GetContextAsync>b__44_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
2023-03-14 09:53:11.316 -05:00 [INF] [SYSTEM] Application shutdown complete
```
Also
```
2023-03-14 09:53:17.284 -05:00 [INF] [MQTT] Initial registration completed
2023-03-14 09:53:34.366 -05:00 [INF] [HASS_API] [automation.turn_on_tv] Performing action: media_play
2023-03-14 09:53:34.389 -05:00 [FTL] [NET] FirstChanceHttpRequestException: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
2023-03-14 09:53:34.390 -05:00 [FTL] [HASS_API] [automation.turn_on_tv] Error while processing action: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
```
And
```
2023-03-14 15:40:40.374 -05:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
```

HASS Agent appears to be connected to the MQTT provider, as both the app and the satellite indicate a successful connection.
![image](https://user-images.githubusercontent.com/26156883/225174286-97eb2846-efac-4f2e-890e-4f1b4881718d.png)
![image](https://user-images.githubusercontent.com/26156883/225174331-0860e61b-7554-4b80-8639-dc1cbb41e673.png)

 I also inspected the activity in the MQTT Broker with MQTTExplorer and I can see HASS Agent publishing information as expected. 
![image](https://user-images.githubusercontent.com/26156883/225174464-b6364dce-f2d4-4b87-9edb-5595ba0736b9.png)

Yet, for some reason Home Assistant won't detect any information on its side.
![image](https://user-images.githubusercontent.com/26156883/225174653-c4a6897d-f660-4e14-a6fb-92a127cabaaf.png)

I've been trying for days now, doing the following:
- Restarting Home Assistant
- Restarting the Mosquitto Addon
- Changing the HASS Agent user credentials
- Reparing the HASS Agent installation

**To Reproduce**
I'm not sure how to reproduce this error

**Expected behavior**
HASS Agent should be able to connect, and be detected by Home Assistant

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://user-images.githubusercontent.com/26156883/225175395-f081796b-9931-4042-b435-47a236bb0dc9.png)

 - Windows' UI language: English
 - HASS.Agent version: 
![image](https://user-images.githubusercontent.com/26156883/225175440-e9c35d91-1c9f-4604-8c8c-7a5beb8d83a0.png)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

I provided the errors I encountered on the logs, but I'd be happy to share the complete logs if there's a need for it :)

Thanks in advance, I really love this project!

**Comment by aristizabal95** [comment]
Found the error. Home Assistant recently changed IP address and the Mosquitto integration was still configured with the previous IP. I was pretty sure this was going to be pretty obvious and I was just missing something. Closing
