### ISSUE TITLE
Bug: Discovery packet for each sensor is resent every 30 seconds

### ISSUE THREAD

**Issue by karwosts** [LAB02-Research/HASS.Agent#295]
**Describe the bug**

My Homeassistant log is overwhelmed with MQTT discovery messages saying its getting discovery for already discovered component. This comes in every 30 seconds, for each HASS.Agent sensor I have configured. 

```
2023-03-17 07:31:17.052 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor TIM-PC tim-pc_loggeduser, sending update
2023-03-17 07:31:47.428 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor TIM-PC tim-pc_loggeduser, sending update
2023-03-17 07:32:17.824 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor TIM-PC tim-pc_loggeduser, sending update
```

Looking in MQTT-Explorer, I confirm a new config packet comes every 30 seconds. 

Why is this happening so often?

**To Reproduce**
1. Create a HASS.Agent sensor
2. ???
3. Get MQTT spam

**Expected behavior**
I would only expect to see one config packet per sensor, at first connection, or when something significant changes that requires a new config packet. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32912880/225936318-2495d0ee-9cd9-4f02-b28b-1b3dfacb9a9a.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 

![image](https://user-images.githubusercontent.com/32912880/225937404-d4d92007-b008-4a72-a152-4fdddd16d07a.png)

 - Windows' UI language: 
 English
 - HASS.Agent version: 
2022.14.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com

**Comment by danielbrunt57** [comment]
I too am seeing this but mine is every 10 seconds, which is the frequency of the lastactive sensor updates.
```
2023-03-24 01:20:34.212 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_lastactive, sending update
2023-03-24 01:20:34.213 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_sessionstate, sending update
2023-03-24 01:20:34.214 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_monitorpowerstate, sending update
2023-03-24 01:20:35.432 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_monitorsleep, sending update
2023-03-24 01:20:35.437 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_monitorwake, sending update
2023-03-24 01:20:35.438 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_restart, sending update
2023-03-24 01:21:04.705 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_lastactive, sending update
2023-03-24 01:21:04.708 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_sessionstate, sending update
2023-03-24 01:21:04.709 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_monitorpowerstate, sending update
2023-03-24 01:21:05.437 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_monitorsleep, sending update
2023-03-24 01:21:05.442 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_monitorwake, sending update
2023-03-24 01:21:05.446 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_restart, sending update
2023-03-24 01:21:35.162 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_lastactive, sending update
2023-03-24 01:21:35.166 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_sessionstate, sending update
2023-03-24 01:21:35.169 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor WINDOWS-11 WINDOWS-11_monitorpowerstate, sending update
2023-03-24 01:21:35.444 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_monitorsleep, sending update
2023-03-24 01:21:35.447 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_monitorwake, sending update
2023-03-24 01:21:35.449 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: button WINDOWS-11 WINDOWS-11_restart, sending update
```

**Comment by NODeeJay** [comment]
I too get this a lot, why is the component "rediscovered" again?

```
2023-06-09 20:46:40.848 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__ConnectionType, sending update
2023-06-09 20:46:40.857 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__UserNotificationStateSensor, sending update
2023-06-09 20:46:40.857 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__CPU, sending update
2023-06-09 20:46:40.858 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__Geolocation, sending update
2023-06-09 20:46:40.859 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__LastBoot, sending update
2023-06-09 20:46:40.860 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__Memory, sending update
2023-06-09 20:46:40.860 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__LastActive, sending update
2023-06-09 20:46:40.861 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__BT_LE_Devices, sending update
2023-06-09 20:46:40.863 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__Microphone_Process, sending update
2023-06-09 20:46:40.863 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: binary_sensor ** **__Microphone_Active, sending update
2023-06-09 20:46:40.864 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: binary_sensor ** **__Webcam_Active, sending update
2023-06-09 20:46:40.865 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **__Webcam_Process, sending update
2023-06-09 20:46:40.881 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_WindowsUpdates_driver_updates_pending, sending update
2023-06-09 20:46:40.881 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_WindowsUpdates_software_updates_pending, sending update
2023-06-09 20:46:40.882 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_WindowsUpdates_driver_updates, sending update
2023-06-09 20:46:40.882 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_WindowsUpdates_software_updates, sending update
2023-06-09 20:46:40.883 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Battery_charge_status, sending update
2023-06-09 20:46:40.883 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Battery_full_charge_lifetime, sending update
2023-06-09 20:46:40.884 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Battery_charge_remaining_percentage, sending update
2023-06-09 20:46:40.884 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Battery_charge_remaining, sending update
2023-06-09 20:46:40.885 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Battery_powerline_status, sending update
2023-06-09 20:46:40.885 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_device, sending update
2023-06-09 20:46:40.886 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_device_state, sending update
2023-06-09 20:46:40.893 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_device_volume, sending update
2023-06-09 20:46:40.893 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_device_muted, sending update
2023-06-09 20:46:40.903 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_peak_volume, sending update
2023-06-09 20:46:40.904 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_audio_sessions, sending update
2023-06-09 20:46:40.915 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_input_device, sending update
2023-06-09 20:46:40.916 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_input_device_state, sending update
2023-06-09 20:46:40.916 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_input_device_muted, sending update
2023-06-09 20:46:40.917 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_Audio_default_input_device_volume, sending update
2023-06-09 20:46:40.917 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_de18243da5874db0881fc1bebe29d316, sending update
2023-06-09 20:46:40.919 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_total_network_card_count, sending update
2023-06-09 20:46:40.920 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_8e00941088334e0298c083ab6efa053e, sending update
2023-06-09 20:46:40.920 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_total_network_card_count, sending update
2023-06-09 20:46:40.921 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_37926b4c49c549b19d4030f20538a5d6, sending update
2023-06-09 20:46:40.932 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor ** **_total_network_card_count, sending update
```

**Comment by pjwerdna** [comment]
Also having the same issues with the discovery message every 30 seconds. Very similar error in the extended log too

```
2023-06-25 11:34:19.829 +01:00 [INF] [MAIN] HASS.Agent version: 2022.14.0
2023-06-25 11:34:19.831 +01:00 [INF] [MAIN] Extended logging enabled
2023-06-25 11:34:19.834 +01:00 [INF] [SETTINGS] Config storage path: C:\Users\me\AppData\Roaming\LAB02 Research\HASS.Agent\config
2023-06-25 11:34:19.927 +01:00 [INF] [SETTINGS] Configuration loaded
2023-06-25 11:34:19.930 +01:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2023-06-25 11:34:20.119 +01:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2023-06-25 11:34:20.138 +01:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2023-06-25 11:34:25.101 +01:00 [INF] [SETTINGS_SENSORS] Loaded 4 entities
2023-06-25 11:34:25.108 +01:00 [INF] [MQTT] Identifying as device: SPEEDY2
2023-06-25 11:34:25.108 +01:00 [INF] [LOCALAPI] Disabled
2023-06-25 11:34:25.111 +01:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2023-06-25 11:34:25.116 +01:00 [INF] [MQTT] Connecting ..
2023-06-25 11:34:25.119 +01:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2023-06-25 11:34:25.140 +01:00 [INF] [MEDIA] Disabled
2023-06-25 11:34:25.214 +01:00 [INF] [NOTIFIER] Ready
2023-06-25 11:34:25.234 +01:00 [INF] [HASS_API] Home Assistant version: 2023.6.2
2023-06-25 11:34:25.317 +01:00 [INF] [MQTT] Connected
2023-06-25 11:34:25.358 +01:00 [INF] [HASS_API] System connected with https://homeassistant.local:8123
2023-06-25 11:34:27.139 +01:00 [INF] [MQTT] Initial registration completed
2023-06-25 11:36:40.202 +01:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)

```
OS Info 
```
Edition	Windows 10 Pro
Version	22H2
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```
Latest HASS.agent and HomeAssistant using mosquitto for MQTT installed on a separate Pi

Always had this error since the first use of HASA.Agent so I've avoided using it up to now.

**Comment by f2daz** [comment]
I have the same problem. Any updates on this one?
Thank you ;)
