### ISSUE TITLE
Problems with Local Sensors

### ISSUE THREAD

**Issue by daniperaleda** [LAB02-Research/HASS.Agent#310]
**Describe the bug**
I have 2 problems with sensors:

1-. The storage sensor in my laptop is not working (curiously no problem in my son one). Do I need to make something special with it? It has not worked in the last 3 months.

2-. I have problems with temperature GPU sensor with this error

Exception raised when updating state of sensor.portatil_dell_gpuload, topic: 'homeassistant/sensor/xxxxxxxl/availability' with payload: b'online'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'NotSupported'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.xxxxxxxxxxxxxx_gputemperatura has device class temperature, state class None unit °C and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: NotSupported (<class 'str'>)
Please check what's applicable (multiple answers possible):

**Comment by amadeo-alex** [comment]
Hello,
Regarding 1:Have you tried recreating the storage sensor? What kind of device/system is the working one and non-working one?
Regarding 2: looks like the same issue as https://github.com/LAB02-Research/HASS.Agent/issues/320 , most likely some change in HA that required modification on HASS.Agent side.

**Comment by amadeo-alex** [comment]
Looks like both GpuLoad and GpuTemperature sensors can return "NotSupported" or "Unknown" in special circumstances which is not an accepted value of temperature.
From my tests correct values are sent later on. Both of them will need to be modified to handle this without returning garbage from "GetState()".
https://github.com/LAB02-Research/HASS.Agent/issues/320 for visibility sake.
