### ISSUE TITLE
No notifications on Windows 11

### ISSUE THREAD

**Issue by psl2806** [LAB02-Research/HASS.Agent#316]
I'm not getting notifications on my Windows 11 client.

In homeassistant I noticed that the client is showing up under MQTT but not under the HASS.agent.

On the client log I can see this:

2023-06-08 13:00:30.493 +02:00 [INF] [HASS_API] Home Assistant version: 2023.6.0
2023-06-08 13:00:30.523 +02:00 [FTL] [PROGRAM] FirstChanceException: Cannot create a stable subkey under a volatile parent key.
System.IO.IOException: Cannot create a stable subkey under a volatile parent key.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
2023-06-08 13:00:30.524 +02:00 [FTL] [NOTIFIER] Error while initializing: Failed initializing notifications
System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: Cannot create a stable subkey under a volatile parent key.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at HASS.Agent.Managers.NotificationManager.Initialize()

**Comment by Ar2rZ** [comment]
same here, no notifications and no mediaplayer also.. sensors are seen and working..

**Comment by amadeo-alex** [comment]
It's good to use the templates when reporting bugs :)
Looks like this is less of a HASS.Agent bug but more of a Windows Community Toolkit issue: https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4858

There is a mention of Windows APP SDK as a potential fix for this but I've not yet checked it out.
