### ISSUE TITLE
no windows popup

### ISSUE THREAD

**Issue by OdinMegan** [LAB02-Research/HASS.Agent#319]
2023-06-11 21:50:33.466 +02:00 [FTL] [NOTIFIER] Error while initializing: Failed initializing notifications
System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: Kan geen stabiele subsleutel maken onder een tijdelijke bovenliggende sleutel.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at HASS.Agent.Managers.NotificationManager.Initialize()
2023-06-11 21:50:34.127 +02:00 [INF] [LOCALAPI] listening on port 5115
2023-06-11 21:50:34.993 +02:00 [INF] [MQTT] Initial registration completed
2023-06-11 21:50:42.823 +02:00 [INF] [NOTIFIER] Attempting to show test notification ..
2023-06-11 21:50:42.827 +02:00 [INF] [NOTIFIER] Test notification attempt completed
2023-06-11 21:51:21.729 +02:00 [INF] [MEDIA] Now playing: Cian Ducrot - I'll Be Waiting

**Comment by amadeo-alex** [comment]
Hello, it'll be easier to help if you'd use the bug report template :)
Looks like a duplicate of https://github.com/LAB02-Research/HASS.Agent/issues/316 with additional issue (I assume whole HASS.Agent window is not appearing for you?)
