### ISSUE TITLE
Bug: Hass.Agent integration part not working...

### ISSUE THREAD

**Issue by Regressor** [LAB02-Research/HASS.Agent#352]
**Describe the bug**
I installed HASS.Agent companion (latest) to my Windows 10 computer and setup mqtt / sensors / commands.
Then I added HASS.Agent integration using HACS (I tried v2022.11.09 and main).

Sensors displays! Commands works (i can put pc to sleep or mute sound or up/down sound volume). 

**But notifications not sent** (local notification test works! and there is no errors in Windows HASS.Agent extended logs) and media player device is in "unavailable" state (media picture loaded once during device adding).

1. Install HASS.Agent.Installer.exe
2. Setup device name and mqtt
3. Install HASS.Agent integration
4. Add auto-descovered device
5. Try to send a notification using developer-tools/service

**Screenshots**
![image](https://github.com/LAB02-Research/HASS.Agent/assets/17557802/7cdbabf2-880e-4918-b42f-8727f0dac440)

![image](https://github.com/LAB02-Research/HASS.Agent/assets/17557802/060fcf41-ae3e-4efb-8b93-2a37ecd97bee)

**Expected behavior**
Notifications works and media player available and can be controlled

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://github.com/LAB02-Research/HASS.Agent/assets/17557802/005ae5c7-2c57-4cec-9c4f-fc290d1985c9)

 - Windows' UI language: RU
 - HASS.Agent version: 2022.14.0 (windows agent)
 - Home Assistant 2023.7.2
 - HASS.Agent integration: v2022.11.09 (and main)
 
 - [x] Installed via installer
 - [x] Problem occurs in HASS.Agent Integration (?)

**Additional context**
I tried to enable local api and home assistant api - no success

**Logs**
I tried to send notification and here logs:

2023-09-13 15:00:28.640 +10:00 [INF] [SYSTEM] Application shutdown complete
2023-09-13 15:00:30.849 +10:00 [INF] [MAIN] HASS.Agent version: 2022.14.0
2023-09-13 15:00:30.855 +10:00 [INF] [MAIN] Extended logging enabled
2023-09-13 15:00:30.860 +10:00 [INF] [SETTINGS] Config storage path: C:\Users\regressor\AppData\Roaming\LAB02 Research\HASS.Agent\config
2023-09-13 15:00:31.045 +10:00 [INF] [SETTINGS] Configuration loaded
2023-09-13 15:00:31.050 +10:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2023-09-13 15:00:31.356 +10:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2023-09-13 15:00:31.397 +10:00 [INF] [SETTINGS_COMMANDS] Loaded 5 entities
2023-09-13 15:00:36.084 +10:00 [INF] [SETTINGS_SENSORS] Loaded 4 entities
2023-09-13 15:00:36.089 +10:00 [INF] [LOCALAPI] Disabled
2023-09-13 15:00:36.091 +10:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2023-09-13 15:00:36.100 +10:00 [INF] [MQTT] Identifying as device: RegHome
2023-09-13 15:00:36.102 +10:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2023-09-13 15:00:36.112 +10:00 [INF] [MQTT] Connecting ..
2023-09-13 15:00:36.180 +10:00 [INF] [MQTT] Connected
2023-09-13 15:00:36.243 +10:00 [INF] [NOTIFIER] Ready
2023-09-13 15:00:36.268 +10:00 [INF] [MEDIA] Ready
2023-09-13 15:00:36.306 +10:00 [INF] [MEDIA] Now playing: birchpunk - BIRCHPUNK
2023-09-13 15:00:36.346 +10:00 [INF] [MEDIA] New state: Paused
2023-09-13 15:00:38.129 +10:00 [INF] [MQTT] Initial registration completed
2023-09-13 15:02:00.896 +10:00 [INF] [MEDIA] Now playing: birchpunk - BIRCHPUNK SPECIAL - AI-VANICH IN THE RUSSIAN CYBERFARM 
2023-09-13 15:02:00.903 +10:00 [INF] [MEDIA] New state: Playing
2023-09-13 15:02:04.938 +10:00 [INF] [MEDIA] Now playing: birchpunk - КИБЕРДЕРЕВНЯ
2023-09-13 15:02:08.970 +10:00 [INF] [MEDIA] New state: Paused
2023-09-13 15:02:51.294 +10:00 [FTL] [PROGRAM] FirstChanceException: Unable to read data from the transport connection: The I/O operation was interrupted due to the end of the command stream or due to an application request.
System.IO.IOException: Unable to read data from the transport connection: The I/O operation was interrupted due to the end of the command stream or due to an application request.
 ---> System.Net.Sockets.SocketException (995): The I/O operation was interrupted due to the end of the command stream or due to an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)

**Comment by Regressor** [comment]
Home assistant log doesn't contain any relates errors.
I just don't know where to start debug this...

**Comment by Regressor** [comment]
Found it. It is because of device name. I named PC as ChildPC and this was wrong. I had to rename it to lower case "childpc", remove MQTT topic named "hass.agent". Remove integration and then reinstall it.

This should be checked when naming device in HASS.Agent settings!

**Comment by amadeo-alex** [comment]
The computer name containing uppercase/having uppercase does not have anything to do with the integration.
This must have been caused by something else. Please list steps required to reproduce the issue if you know them.

**Comment by Regressor** [comment]
I checked this three times (i have 3 computers). Only lower case works (i.e. ChildPC -> childpc). If you sure computer name case is not a reason - i'll close this.
