### ISSUE TITLE
Bug: Powershell Sensor stay "unknown" after HA restart or reload of integration

### ISSUE THREAD

**Issue by Zarox666** [LAB02-Research/HASS.Agent#361]
**Describe the bug**
When restarting HA, or reloading the MQTT Integratrion 
any Powershell Sensor remains in an "unknown" state afterwards.
When loging on to the Windows System and clicking on Send & Activate Sensors it imediately starts working again.
This applies to sensors from the Service as well as from the Agent.
Non-Powershell Sensors such as CPU Load do reconnect automaticaly.

Not sure if it is related, but also removed Sensors do not disappear (or become deletable) in HA even so there are no Sensors in HASS Agent or Satelite Service anymore.

**To Reproduce**
Reload integration:
![image](https://github.com/LAB02-Research/HASS.Agent/assets/115449639/99ef2eff-fac5-4419-8e45-aa8bac97d422)

Sensor unknown:
![image](https://github.com/LAB02-Research/HASS.Agent/assets/115449639/42597582-87be-4ece-954b-e734edfafc18)

Send & Activate Sensors:
![image](https://github.com/LAB02-Research/HASS.Agent/assets/115449639/19e120cb-e381-429c-aec6-c547a0160b0b)

Sensor working again:
![image](https://github.com/LAB02-Research/HASS.Agent/assets/115449639/fca01948-253c-4545-b426-42a33ad501c9)

**Expected behavior**
Powershell Sensors should resume working like any other Sensor after reload of the MQTT integration or HA restart.

**Screenshots**
see above

**Misc info (please complete the following information):**
 - Windows Server 2022 21H2
 - HASS.Agent version: 2022.14.0
 - Satelite Service Version: 2022.20.0.0

**Logs**
HASS Satelite Service log for today:
<-- Start of Logfile -->
2023-10-05 08:27:10.035 +02:00 [INF] [SENSORSMANAGER] Processing 2 received sensor(s), deleting 0 sensor(s) ..
2023-10-05 08:27:10.333 +02:00 [FTL] [SENSORSMANAGER] Error while publishing: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at HASS.Agent.Satellite.Service.Sensors.SensorsManager.Process()
2023-10-05 08:27:10.360 +02:00 [INF] [SENSORS] Modified single-value sensor: MinerInstances
2023-10-05 08:27:10.362 +02:00 [INF] [SENSORS] Modified single-value sensor: CPULoad
2023-10-05 08:27:10.362 +02:00 [INF] [SETTINGS_SENSORS] Stored 2 entities

<-- Reload of MQTT -->

2023-10-05 08:29:23.817 +02:00 [INF] [MQTT] Connected
2023-10-05 08:33:15.633 +02:00 [INF] [SENSORSMANAGER] Processing 2 received sensor(s), deleting 0 sensor(s) ..
2023-10-05 08:33:15.950 +02:00 [INF] [SENSORS] Modified single-value sensor: MinerInstances
2023-10-05 08:33:15.951 +02:00 [INF] [SENSORS] Modified single-value sensor: CPULoad
2023-10-05 08:33:15.952 +02:00 [INF] [SETTINGS_SENSORS] Stored 2 entities

<-- End of Logfile -->

**Comment by Zarox666** [comment]
has someone looked into this allready?

**Comment by Zarox666** [comment]
any update on this?

**Comment by EpicLPer** [comment]
For me it constantly says "Unknown".

**Comment by Zarox666** [comment]
I gave up waiting for this to be fixed, and instead use HAs RestAPI from Powershell directly:
https://developers.home-assistant.io/docs/api/rest/

What I havent yet figured out, is how I can wait with Powershell for an Event triggered by HA.
Once I have that, I can finaly uninstall the HASS Agent.

**Comment by EpicLPer** [comment]
> I gave up waiting for this to be fixed, and instead use HAs RestAPI from Powershell directly: https://developers.home-assistant.io/docs/api/rest/
> 
> What I havent yet figured out, is how I can wait with Powershell for an Event triggered by HA. Once I have that, I can finaly uninstall the HASS Agent.

I mean, for your specific case the first thing coming to mind is: You simply start the PowerShell script via a command from Hass.Agent, this way you don't have to wait for anything inside your script.

**Comment by EpicLPer** [comment]
And on another note: There is a newer fork of HASS.Agent that is trying to make it a better project, maybe worth a look for you: https://github.com/hass-agent/HASS.Agent
Same bug there so far but I reported it just a few minutes ago, hopefully they'll take a look at it :)
