### ISSUE TITLE
Can't add MultipleKeysCommand

### ISSUE THREAD

**Issue by CrazyCoder** [LAB02-Research/HASS.Agent#365]
Unhandled exception when trying to add MultipleKeysCommand:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Extensions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Windows.Extensions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Syncfusion.Windows.Forms.MessageBoxFormAdv.InitializeImage(Image image, Size sizeImage)
   at Syncfusion.Windows.Forms.MessageBoxFormAdv..ctor(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean bShowHelpButton, CancelEventHandler helpButtonClickHandler, Image image, Size sizeImage)
   at Syncfusion.Windows.Forms.MessageBoxAdv.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp, CancelEventHandler helpButtonClickHandler, Image image, Size imageSize)
   at Syncfusion.Windows.Forms.MessageBoxAdv.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp, CancelEventHandler helpButtonClickHandler)
   at Syncfusion.Windows.Forms.MessageBoxAdv.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at Syncfusion.Windows.Forms.MessageBoxAdv.Show(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon)
   at HASS.Agent.Forms.Commands.CommandsMod.BtnStore_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Private.CoreLib.dll
----------------------------------------
HASS.Agent
    Assembly Version: 2022.14.0.0
    Win32 Version: 2022.14.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/HASS.Agent.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.dll
----------------------------------------
Syncfusion.Licensing
    Assembly Version: 20.3.0.50
    Win32 Version: 20.3.0.50
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Syncfusion.Licensing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/System.Drawing.Common.dll
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Text.Encoding.CodePages.dll
----------------------------------------
Syncfusion.Shared.Base
    Assembly Version: 20.3500.0.50
    Win32 Version: 20.3500.0.50
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Syncfusion.Shared.Base.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Collections.Specialized.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.12.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Serilog.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Collections.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Linq.dll
----------------------------------------
Serilog.Sinks.Async
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Serilog.Sinks.Async.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/netstandard.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.Http.dll
----------------------------------------
HotkeyListener
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/HotkeyListener.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/mscorlib.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1370.28
    Win32 Version: 1.0.1370.28
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Microsoft.Web.WebView2.Core.dll
----------------------------------------
HASS.Agent.Shared
    Assembly Version: 2022.24.0.0
    Win32 Version: 2022.24.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/HASS.Agent.Shared.dll
----------------------------------------
MQTTnet
    Assembly Version: 3.1.2.0
    Win32 Version: 3.1.2
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/MQTTnet.dll
----------------------------------------
Grapeseed
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Grapeseed.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Threading.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/Microsoft.Win32.Registry.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Serilog.Sinks.File.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Text.RegularExpressions.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.IO.FileSystem.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Memory.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Reflection.Primitives.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Collections.Concurrent.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Diagnostics.TraceSource.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Newtonsoft.Json.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.Numerics.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.ComponentModel.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Private.CoreLib.dll
----------------------------------------
CoreAudio
    Assembly Version: 2022.10.23.104
    Win32 Version: 2022.10.23.104
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/CoreAudio.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Threading.Thread.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Collections.NonGeneric.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/Accessibility.dll
----------------------------------------
Syncfusion.Tools.Windows
    Assembly Version: 20.3500.0.50
    Win32 Version: 20.3500.0.50
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Syncfusion.Tools.Windows.dll
----------------------------------------
Syncfusion.Core.WinForms
    Assembly Version: 20.3500.0.50
    Win32 Version: 20.3500.0.50
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Syncfusion.Core.WinForms.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/Microsoft.Win32.SystemEvents.dll
----------------------------------------
HASS.Agent.resources
    Assembly Version: 2022.14.0.0
    Win32 Version: 2022.14.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/en/HASS.Agent.resources.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/System.Drawing.dll
----------------------------------------
HASS.Agent.Shared.resources
    Assembly Version: 2022.24.0.0
    Win32 Version: 2022.24.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/en/HASS.Agent.Shared.resources.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Threading.ThreadPool.dll
----------------------------------------
Grapevine
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Grapevine.dll
----------------------------------------
MQTTnet.Extensions.ManagedClient
    Assembly Version: 3.1.2.0
    Win32 Version: 3.1.2
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/MQTTnet.Extensions.ManagedClient.dll
----------------------------------------
HADotNet.Core
    Assembly Version: 1.6.0.0
    Win32 Version: 1.6.0.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/HADotNet.Core.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.ServiceProcess.ServiceController
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/System.ServiceProcess.ServiceController.dll
----------------------------------------
Microsoft.Windows.SDK.NET
    Assembly Version: 10.0.17763.24
    Win32 Version: 10.0.17763.27
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Microsoft.Windows.SDK.NET.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.Sockets.dll
----------------------------------------
WinRT.Runtime
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.39961
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/WinRT.Runtime.dll
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Assembly Version: 7.1.0.0
    Win32 Version: 7.1.2.1
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Microsoft.Toolkit.Uwp.Notifications.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Threading.Overlapped.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.NameResolution.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Reflection.Emit.dll
----------------------------------------
DynamicComActivator
    Assembly Version: 0.0.0.0
    Win32 Version: 7.1.2.1
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Microsoft.Toolkit.Uwp.Notifications.dll
----------------------------------------
System.Security.Cryptography.Csp
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Cryptography.Csp.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Claims.dll
----------------------------------------
Snippets
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Linq.Expressions.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Text.Json.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.Intrinsics.dll
----------------------------------------
Octokit
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1.0
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Octokit.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.IO.Compression.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Security.Permissions
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.23/System.Security.Permissions.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Runtime.Loader.dll
----------------------------------------
System.Net.NetworkInformation
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.NetworkInformation.dll
----------------------------------------
Syncfusion.Grid.Windows
    Assembly Version: 20.3500.0.50
    Win32 Version: 20.3500.0.50
    CodeBase: file:///C:/Users/serge/AppData/Roaming/LAB02%20Research/HASS.Agent/Syncfusion.Grid.Windows.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Core.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 6.0.0.0
    Win32 Version: n/a
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.23/System.Net.Quic.dll
----------------------------------------

************** JIT Debugging **************



```

**Comment by amadeo-alex** [comment]
Hello,
Could you please edit the issue and use the "issue template"?
This will provide more information like window version & installation method.

**Comment by CrazyCoder** [comment]
Windows 10, installed via the official installer.

Anyway, I downloaded the sources, recompiled it from the source, and it now works without this error.

**Comment by amadeo-alex** [comment]
That is strange, the only "normal way" to have this kind of error is to have the files removed. Interesting how this might have happened.
Good that it got you working though :)
