### ISSUE TITLE
Bug: Detected that custom integration 'hass_agent' calls async_create_task from a thread

### ISSUE THREAD

**Issue by Jonny-T-cyber** [LAB02-Research/HASS.Agent#411]
Hi!
In the logs I have a lot of errors like this:

```
2024-05-05 19:20:47.751 ERROR (SyncWorker_18) [homeassistant.util.logging] Exception in updated when handling msg on 'hass.agent/devices/DELL-XPS': '{"serial_number":"a22eb536-c455-4789-9996-dd2ee52e5b9c","device":{"identifiers":"hass.agent-DELL-XPS","manufacturer":"HASS.Agent Team","model":"Microsoft Windows NT 10.0.22631.0","name":"DELL-XPS","sw_version":"2.0.1"},"apis":{"notifications":true,"media_player":true}}'
Traceback (most recent call last):
  File "/config/custom_components/hass_agent/__init__.py", line 147, in updated
    hass.async_create_task(handle_apis_changed(hass, entry, apis))
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'hass_agent' calls async_create_task from a thread at custom_components/hass_agent/__init__.py, line 147: hass.async_create_task(handle_apis_changed(hass, entry, apis)). Please report it to the author of the 'hass_agent' custom integration.
```

**Comment by Chaoscontrol** [comment]
Same here since updating from HA core 2024.4.4 to 2024.5.1.
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 5 May 2024 at 22:41:02 (140 occurrences)
Last logged: 09:46:25

Detected that custom integration 'hass_agent' calls async_create_task from a thread at custom_components/hass_agent/__init__.py, line 147: hass.async_create_task(handle_apis_changed(hass, entry, apis)), please report it to the author of the 'hass_agent' custom integration
```
And
```
Logger: homeassistant.util.logging
Source: util/logging.py:98
First occurred: 5 May 2024 at 22:41:02 (140 occurrences)
Last logged: 09:46:25

Exception in updated when handling msg on 'hass.agent/devices/LegionLaptop': '{"serial_number":"c989177b-d3fd-44cf-a51e-4c518069bda0","device":{"identifiers":"hass.agent-LegionLaptop","manufacturer":"LAB02 Research","model":"Microsoft Windows NT 10.0.22635.0","name":"LegionLaptop","sw_version":"2022.14.0"},"apis":{"notifications":true,"media_player":true}}' Traceback (most recent call last): File "/config/custom_components/hass_agent/__init__.py", line 147, in updated hass.async_create_task(handle_apis_changed(hass, entry, apis)) File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task self.verify_event_loop_thread("async_create_task") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'hass_agent' calls async_create_task from a thread at custom_components/hass_agent/__init__.py, line 147: hass.async_create_task(handle_apis_changed(hass, entry, apis)). Please report it to the author of the 'hass_agent' custom integration.
```

**Comment by Nelsun23** [comment]
I noticed similar log entries today too. Curiously, I have 2 agent instances but only seeing log entries for one of them. Entries repeat roughly every 30 seconds.

Both use satellite service sensors which, on the offending instance, I've changed the satellite sensor reporting times to high numbers (e.g. 3000 seconds) but the log entries remain at 30 second intervals. There are no normal sensors in use on said offending instance.

Both are running the same latest versions. The main difference between the two is the OS: Win 10 Pro 22H2 for the log entry one and Win 11 Pro 23H2 for the other.

HASS
Agent: 2022.14.0
Satellite: : 2022.20.0.0

HA
Core: 2024.5.2
Supervisor: 2024.04.4
Operating System: 12.2
Frontend: 20240501.0

**Comment by derhappy** [comment]
Same issue here with 2024.5.2

```
Logger: homeassistant.util.logging
Quelle: util/logging.py:98
Erstmals aufgetreten: 09:57:54 (10 Vorkommnisse)
Zuletzt protokolliert: 10:02:25

Exception in updated when handling msg on 'hass.agent/devices/WORKSTATION01': '{"serial_number":"6c08fd9b-f997-499c-8e04-......","device":{"identifiers":"hass.agent-WORKSTATION01","manufacturer":"LAB02 Research","model":"Microsoft Windows NT 10.0.22631.0","name":"WORKSTATION01","sw_version":"2022.14.0"},"apis":{"notifications":true,"media_player":true}}' Traceback (most recent call last): File "/config/custom_components/hass_agent/__init__.py", line 147, in updated hass.async_create_task(handle_apis_changed(hass, entry, apis)) File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task self.verify_event_loop_thread("async_create_task") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'hass_agent' calls async_create_task from a thread at custom_components/hass_agent/__init__.py, line 147: hass.async_create_task(handle_apis_changed(hass, entry, apis)). Please report it to the author of the 'hass_agent' custom integration.
```

and also

```
Logger: py.warnings
Quelle: util/logging.py:120
Erstmals aufgetreten: 09:57:54 (10 Vorkommnisse)
Zuletzt protokolliert: 10:02:25

/usr/src/homeassistant/homeassistant/util/logging.py:120: RuntimeWarning: coroutine 'handle_apis_changed' was never awaited log_exception(format_err, *args)
```

**Comment by cvincent** [comment]
I'm seeing the same messages in my HA logs. Possibly related to my HASS.Agent notifications no longer working.

**Comment by aredon** [comment]
Can confirm, but there's also a warning line above the error line that I haven't seen anyone else post yet:

> 2024-05-08 10:50:58.480 WARNING (SyncWorker_46) [homeassistant.helpers.frame] Detected that custom integration 'hass_agent' calls async_create_task from a thread at custom_components/hass_agent/__init__.py, line 147: hass.async_create_task(handle_apis_changed(hass, entry, apis)), please report it to the author of the 'hass_agent' custom integration

**Comment by catgirlkara** [comment]
This is happening to me too!

**Comment by obidobi** [comment]
Ah. I just installed HASS.Agent for the first time and could not get it to work.
Got no instance with media_player entity and notifiy service.

Just noticed this Exception in the log to. So I guess HASS.Agent is broken with newest HA?

**Comment by aredon** [comment]
> Ah. I just installed HASS.Agent for the first time and could not get it to work. Got no instance with media_player entity and notifiy service.
> 
> Just noticed this Exception in the log to. So I guess HASS.Agent is broken with newest HA?

Nah it's mostly working. Just this issue.

**Comment by amadeo-alex** [comment]
Media player and notifications will not work - you can use those steps to get around this https://github.com/hass-agent/HASS.Agent-Integration/issues/2

**Comment by amaisano** [comment]
Noticing these all month. It is causing my RPi4 with 4GB RAM to crash/reboot multiple times a day.

**Comment by mccmax1395** [comment]
> Noticing these all month. It is causing my RPi4 with 4GB RAM to crash/reboot multiple times a day.

Just go through the steps linked by amadeo-alex.  I did that and it fixed my issue

**Comment by ThomasCr** [comment]
I suffer from the same problem. Is there a final solution we can install with HACS?

**Comment by Chaoscontrol** [comment]
This has not been updated since 2022 mate, don't expect much. Apply the fix manually and live on.

**Comment by amadeo-alex** [comment]
> I suffer from the same problem. Is there a final solution we can install with HACS?

You can install the forked version of integration: https://github.com/hass-agent/HASS.Agent-Integration (needs to be added as a custom repository)
In case of questions about the fork: https://github.com/hass-agent/hass.agent?tab=readme-ov-file#fork

**Comment by Chaoscontrol** [comment]
Didn't know about it, thanks!
