### ISSUE TITLE
Bug: QuickActions not working in 2022.11.0-beta1

### ISSUE THREAD

**Issue by nrsfhass** [LAB02-Research/HASS.Agent#47]
2022-04-15 14:52:12.639 -03:00 [INF] [MQTT] Connecting ..
2022-04-15 14:52:12.714 -03:00 [INF] [MQTT] Connected
2022-04-15 14:52:12.827 -03:00 [INF] [HASS_API] Home Assistant version: 2022.4.4
2022-04-15 14:52:13.051 -03:00 [INF] [NOTIFIER] API listening on port 5115
2022-04-15 14:52:13.759 -03:00 [INF] [HASS_API] System connected with https://xxxxxx.duckdns.org:8123/
2022-04-15 14:52:14.651 -03:00 [INF] [MQTT] Initial registration completed
2022-04-15 14:52:15.600 -03:00 [INF] [HASS_API] [.agua] Performing action: 
2022-04-15 14:52:15.636 -03:00 [FTL] [HASS_API] [.agua] Error while processing action: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
2022-04-15 14:52:16.782 -03:00 [WRN] [HASS_API] Server returned 404 (not found) while getting entity state. This can happen after a server reboot, or if you've deleted the entity. If the problem persists, please file a ticket on github.
Entity: light.agua
Error message: Response status code does not indicate success: 404 (Not Found).

**Comment by LAB02-Admin** [comment]
Yep bug in the latest beta, will fix!

**Comment by LAB02-Admin** [comment]
Fixed in the latest beta: 

https://github.com/LAB02-Research/HASS.Agent/releases/tag/b2022.11.1

**Comment by nrsfhass** [comment]
Thanks
