### ISSUE TITLE
Crash after start-up

### ISSUE THREAD

**Issue by GegoSK** [LAB02-Research/HASS.Agent#60]
Hello again :),
I am not sure, what happened today (windows update?), but HASS.Agent did not start. This is the error: 
![image](https://user-images.githubusercontent.com/65870850/166555217-d549bc28-3cd5-487a-90ba-3305c63e1cbd.png)
When I press OK:
![image](https://user-images.githubusercontent.com/65870850/166555276-ca065ad0-d41f-448b-ae5b-b4f5679ec211.png) 
Again OK and crash. 

Log file:
```
2022-05-03 21:51:40.008 +02:00 [INF] [SYSTEM] Application shutting down
2022-05-03 21:51:40.012 +02:00 [INF] [MQTT] Disconnected
2022-05-03 21:51:40.017 +02:00 [INF] [SYSTEM] Application shutdown complete
2022-05-03 21:52:55.147 +02:00 [INF] [SETTINGS] Config storage path: C:\Programové súbory Gego\HASS.Agent\config
2022-05-03 21:52:55.247 +02:00 [INF] [SETTINGS] Configuration loaded
2022-05-03 21:52:55.249 +02:00 [INF] [LOCALIZTION] No language setting stored, falling back to the system's UI culture: slovenčina (Slovensko)
2022-05-03 21:52:55.249 +02:00 [WRN] [LOCALIZATION] The selected UI culture isn't yet supported, please help out by translating:
2022-05-03 21:52:55.249 +02:00 [WRN] [LOCALIZATION] https://github.com/LAB02-Research/HASS.Agent/wiki/Translating
2022-05-03 21:52:55.250 +02:00 [INF] [LOCALIZATION] Setting default: angličtina
2022-05-03 21:52:55.452 +02:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 2 entities
2022-05-03 21:52:55.464 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 7 entities
2022-05-03 21:52:59.998 +02:00 [FTL] [SETTINGS_SENSORS] Error loading entities: PerformanceCounter not found
System.Exception: PerformanceCounter not found
   at HASS.Agent.Shared.Models.HomeAssistant.Sensors.PerformanceCounterSensor..ctor(String categoryName, String counterName, String instanceName, Nullable`1 updateInterval, String name, String id)
   at HASS.Agent.Shared.Models.HomeAssistant.Sensors.PerfCounterSensors.SingleValue.CpuLoadSensor..ctor(Nullable`1 updateInterval, String name, String id)
   at HASS.Agent.Settings.StoredSensors.ConvertConfiguredToAbstractSingleValue(ConfiguredSensor sensor)
   at HASS.Agent.Settings.StoredSensors.<>c__DisplayClass0_0.<LoadAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at HASS.Agent.Settings.StoredSensors.LoadAsync()
```

After checking all 4 json files in Config directory. Only solution was delete sensor: 
```
  {
    "Type": "CpuLoadSensor",
    "Id": "2c01a6c6-2fea-4589-8192-00f82476265b",
    "UpdateInterval": 30,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "Processor",
    "Counter": "% Processor Time",
    "Instance": "_Total",
    "Name": "CpuLoad"
  },
```
from sensor.json file. Then HASS.Agent started but satellite service did not. 
![image](https://user-images.githubusercontent.com/65870850/166556032-b478ce68-3405-4a23-b595-fd6d6a07329b.png)

Log file after change in sensor,json file:
```
2022-05-03 22:00:13.020 +02:00 [INF] [SYSTEM] Application shutting down
2022-05-03 22:00:13.024 +02:00 [INF] [MQTT] Disconnected
2022-05-03 22:00:13.028 +02:00 [INF] [SYSTEM] Application shutdown complete
2022-05-03 22:00:14.383 +02:00 [INF] [SETTINGS] Config storage path: C:\Programové súbory Gego\HASS.Agent\config
2022-05-03 22:00:14.487 +02:00 [INF] [SETTINGS] Configuration loaded
2022-05-03 22:00:14.489 +02:00 [INF] [LOCALIZTION] No language setting stored, falling back to the system's UI culture: slovenčina (Slovensko)
2022-05-03 22:00:14.489 +02:00 [WRN] [LOCALIZATION] The selected UI culture isn't yet supported, please help out by translating:
2022-05-03 22:00:14.489 +02:00 [WRN] [LOCALIZATION] https://github.com/LAB02-Research/HASS.Agent/wiki/Translating
2022-05-03 22:00:14.489 +02:00 [INF] [LOCALIZATION] Setting default: angličtina
2022-05-03 22:00:14.686 +02:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 2 entities
2022-05-03 22:00:14.701 +02:00 [INF] [SETTINGS_COMMANDS] Loaded 7 entities
2022-05-03 22:00:19.126 +02:00 [FTL] [WUPDATE] Unable to query update status, Windows update seems to be corrupt: 0x80248014
System.Runtime.InteropServices.COMException (0x80248014): 0x80248014
   at WUApiLib.IUpdateSearcher.Search(String criteria)
   at HASS.Agent.Shared.Functions.WindowsUpdatesManager.GetUpdateList()
2022-05-03 22:00:19.218 +02:00 [INF] [SETTINGS_SENSORS] Loaded 15 entities
2022-05-03 22:00:19.226 +02:00 [INF] [NOTIFIER] Initializing local API ..
2022-05-03 22:00:19.227 +02:00 [INF] [SERVICE] Local install path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-05-03 22:00:19.227 +02:00 [INF] [MQTT] Identifying as device: PCGEGO
2022-05-03 22:00:19.230 +02:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2022-05-03 22:00:19.230 +02:00 [INF] [HOTKEY] Completed bind for 2 individual quickaction hotkeys
2022-05-03 22:00:19.233 +02:00 [INF] [MQTT] Connecting ..
2022-05-03 22:00:19.283 +02:00 [INF] [MQTT] Connected
2022-05-03 22:00:19.324 +02:00 [INF] [HASS_API] Home Assistant version: 2022.4.7
2022-05-03 22:00:19.462 +02:00 [INF] [NOTIFIER] API listening on port 5115
2022-05-03 22:00:21.266 +02:00 [INF] [MQTT] Initial registration completed
2022-05-03 22:00:22.148 +02:00 [INF] [HASS_API] System connected with http://homeassistant.local:8123
2022-05-03 22:00:25.174 +02:00 [WRN] [HASS_API] Server returned 404 (not found) while getting entity state. This can happen after a server reboot, or if you've deleted the entity. If the problem persists, please file a ticket on github.
Entity: switch.mediaplaypause
Error message: Response status code does not indicate success: 404 (Not Found).
```

There is switch.mediaplaypause. A week ago, I changed the switches to buttones. 

Hope this help. If you need more information, let me know.

**Comment by LAB02-Admin** [comment]
Hi @GegoSK,

I actually had the same problem! It's caused by corrupt performance counters. It's easy to fix, I've written a wiki page for it:

https://github.com/LAB02-Research/HASS.Agent/wiki/Performance-Counter-Debugging

I'll add a 'fix performance counters' button to my todo list, but for now hopefully this fixes it for you. Let me know if it doesn't!

**Comment by GegoSK** [comment]
@LAB02-Admin Thank you very much for respond. Today everything works without problem. Even with CpuLoadSensor. Add yes, I restarted PC, yesterday.  
To be honest, I should wait for few days, whether it will be fix by itself.
