### ISSUE TITLE
Bug: PerformanceCounter not found

### ISSUE THREAD

**Issue by tinbob** [LAB02-Research/HASS.Agent#76]
**Describe the bug**
Unable to add sensors.

Please check what's applicable (multiple answers possible):
 - [x] Installed via installer
 - [x] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Logs**
[FTL] [SENSORSMANAGER] Error while storing: PerformanceCounter not found
System.Exception: PerformanceCounter not found
   at HASS.Agent.Shared.HomeAssistant.Sensors.PerformanceCounterSensor..ctor(String categoryName, String counterName, String instanceName, Nullable`1 updateInterval, String name, String id)
   at HASS.Agent.Shared.HomeAssistant.Sensors.PerfCounterSensors.SingleValue.CpuLoadSensor..ctor(Nullable`1 updateInterval, String name, String id)
   at HASS.Agent.Settings.StoredSensors.ConvertConfiguredToAbstractSingleValue(ConfiguredSensor sensor)
   at HASS.Agent.Sensors.SensorsManager.StoreAsync(List`1 sensors, List`1 toBeDeletedSensors)

**Comment by velaar** [comment]
Having this exact issue on 2022.14 

Here ls the log: 


```
2023-01-29 22:48:11.903 -07:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2023-01-29 22:48:12.085 -07:00 [FTL] [SETTINGS_SENSORS] Error loading entities: PerformanceCounter not found
System.Exception: PerformanceCounter not found
   at HASS.Agent.Shared.HomeAssistant.Sensors.PerformanceCounterSensor..ctor(String categoryName, String counterName, String instanceName, Nullable`1 updateInterval, String name, String id)
   at HASS.Agent.Shared.HomeAssistant.Sensors.PerfCounterSensors.SingleValue.CpuLoadSensor..ctor(Nullable`1 updateInterval, String name, String id)
   at HASS.Agent.Satellite.Service.Settings.StoredSensors.ConvertConfiguredToAbstractSingleValue(ConfiguredSensor sensor)
   at HASS.Agent.Satellite.Service.Settings.StoredSensors.<>c__DisplayClass0_0.<LoadAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at HASS.Agent.Satellite.Service.Settings.StoredSensors.LoadAsync()
```

**Comment by velaar** [comment]
Resolved for me by following [this guide](https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters)
