### ISSUE TITLE
Bug: satellite service stops after short period

### ISSUE THREAD

**Issue by sdwilsh** [LAB02-Research/HASS.Agent#95]
The satellite service only stays up for a short time before it goes away.  Unfortunately, the logs are not very helpful, as they just show this:
```
2022-06-25 15:45:13.414 -07:00 [INF] [MAIN] Version: 2022.13.0.0
2022-06-25 15:45:13.424 -07:00 [INF] [MAIN] Service started, initializing ..
2022-06-25 15:45:13.492 -07:00 [INF] [MAIN] Running as a service, initializing lifetime manager
2022-06-25 15:45:13.518 -07:00 [INF] [LIFETIMEMANAGER] Initialized
2022-06-25 15:45:13.533 -07:00 [INF] [WORKER] Startup completed, commencing execution ..
2022-06-25 15:45:13.535 -07:00 [INF] [SETTINGS] Config storage path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\config
2022-06-25 15:45:13.606 -07:00 [INF] [SETTINGS] Configuration loaded
2022-06-25 15:45:13.610 -07:00 [INF] [SETTINGS] MQTT configuration loaded
2022-06-25 15:45:13.611 -07:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2022-06-25 15:45:13.634 -07:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\
2022-06-25 15:45:14.286 -07:00 [INF] [SETTINGS_SENSORS] Loaded 2 entities
2022-06-25 15:45:14.289 -07:00 [INF] [MQTT] Identifying as device: sdwilsh_desktop-satellite
2022-06-25 15:45:14.296 -07:00 [INF] [MQTT] Connecting ..
2022-06-25 15:45:14.307 -07:00 [INF] [RPCMANAGER] Listening
2022-06-25 15:45:14.334 -07:00 [INF] [MQTT] Connected
```

I'm not sure what I can provide you with to help figure out what is going on, but I suspect more logging needs to be added to figure this out.

**Expected behavior**
Satellite service continues to run.

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 21H2 (OS Build 19044.1766)
 - Windows' UI language: En_us
 - HASS.Agent version: 2022.12.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
What sensors d'you have configured for the satellite service?

**Comment by LAB02-Admin** [comment]
It's already possible to enable extended logging, but currently requires a few steps. First, enable it in HASS.Agent itself:

![image](https://user-images.githubusercontent.com/81011038/175805971-c182d2db-803a-4ba7-98d6-0dd4bb274a8b.png)

Then stop the service if it's running:

![image](https://user-images.githubusercontent.com/81011038/175805984-4a08f434-66d8-4162-a323-971de551d67d.png)

Lastly, go to the following folder:

`C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service`

and manually launch `HASS.Agent.Satellite.Service.exe` elevated (by right-clicking and selecting `Run as administrator`).

Make sure to disable extended logging in HASS.Agent when you're done, as it can make the logs grow quite large.

**Comment by sdwilsh** [comment]
It wasn't clear that changing the logging detail of the agent would update the service too.  It might be worth adding a note there.

> What sensors d'you have configured for the satellite service?

I only have two right now, but I did have two others that I created just before these issues started up.  I created two different network ones for specific networks I wanted to have.

```json
[
  {
    "Type": "CpuLoadSensor",
    "Id": "53366abf-b00b-47fe-a4fa-a601c3f9b13b",
    "UpdateInterval": 30,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "Processor",
    "Counter": "% Processor Time",
    "Instance": "_Total",
    "Name": "sdwilsh_desktop_satellite_cpuload"
  },
  {
    "Type": "GpuLoadSensor",
    "Id": "24fdad55-c3de-4725-b90c-16890283c8fa",
    "UpdateInterval": 30,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "",
    "Counter": "",
    "Instance": "",
    "Name": "sdwilsh_desktop_satellite_gpuload"
  }
]
```


The extended logs gave something a little more interesting:
```
2022-06-26 14:25:10.436 -07:00 [INF] [MAIN] Version: 2022.13.0.0
2022-06-26 14:25:10.449 -07:00 [INF] [MAIN] Extended logging enabled
2022-06-26 14:25:10.449 -07:00 [INF] [MAIN] Service started, initializing ..
2022-06-26 14:25:11.193 -07:00 [INF] [MAIN] Not running as a service, skipping lifetime manager
2022-06-26 14:25:11.230 -07:00 [INF] [WORKER] Startup completed, commencing execution ..
2022-06-26 14:25:11.231 -07:00 [INF] [SETTINGS] Config storage path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service\config
2022-06-26 14:25:11.399 -07:00 [INF] [SETTINGS] Configuration loaded
2022-06-26 14:25:11.407 -07:00 [INF] [SETTINGS] MQTT configuration loaded
2022-06-26 14:25:11.408 -07:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2022-06-26 14:25:11.431 -07:00 [INF] Application started. Press Ctrl+C to shut down.
2022-06-26 14:25:11.433 -07:00 [INF] Hosting environment: Production
2022-06-26 14:25:11.433 -07:00 [INF] Content root path: C:\Program Files (x86)\LAB02 Research\HASS.Agent Satellite Service
2022-06-26 14:25:12.268 -07:00 [FTL] [PROGRAM] FirstChanceException: Unable to load DLL 'nvapi64.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
System.DllNotFoundException: Unable to load DLL 'nvapi64.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at LibreHardwareMonitor.Interop.NvApi.NvAPI64_QueryInterface(UInt32 interfaceId)
   at LibreHardwareMonitor.Interop.NvApi.GetDelegate[T](UInt32 id, T& newDelegate)
2022-06-26 14:25:12.480 -07:00 [INF] [SETTINGS_SENSORS] Loaded 2 entities
2022-06-26 14:25:12.520 -07:00 [INF] [MQTT] Identifying as device: sdwilsh_desktop-satellite
2022-06-26 14:25:12.649 -07:00 [INF] [MQTT] Connecting ..
2022-06-26 14:25:12.659 -07:00 [INF] [RPCMANAGER] Not running as a service, current user granted full control: sdwilsh
2022-06-26 14:25:12.665 -07:00 [INF] [RPCMANAGER] Listening
2022-06-26 14:25:12.691 -07:00 [INF] [MQTT] Connected
```
I reinstalled the service, and it appears to be running now.  Let me try adding the sensors back and see what happens.

**Comment by sdwilsh** [comment]
Okay, I think I may have tracked down part of what might have caused this.  I've created two network sensors:
![image](https://user-images.githubusercontent.com/656602/175834805-5ab1c7ab-4b8f-417a-b8cf-84bd8d71c9e2.png)
![image](https://user-images.githubusercontent.com/656602/175834823-05094bbd-f38b-4c79-b4af-1203ee6934d5.png)

Full list of sensors in the UX:
![image](https://user-images.githubusercontent.com/656602/175834839-b4dbf68e-2421-400a-abfc-b04ac3481594.png)

However, if I look at the `sensors.json` file, it only has one network sensor (even after I send and activate sensors):
```json
[
  {
    "Type": "CpuLoadSensor",
    "Id": "53366abf-b00b-47fe-a4fa-a601c3f9b13b",
    "UpdateInterval": 30,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "Processor",
    "Counter": "% Processor Time",
    "Instance": "_Total",
    "Name": "sdwilsh_desktop_satellite_cpuload"
  },
  {
    "Type": "GpuLoadSensor",
    "Id": "24fdad55-c3de-4725-b90c-16890283c8fa",
    "UpdateInterval": 30,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "",
    "Counter": "",
    "Instance": "",
    "Name": "sdwilsh_desktop_satellite_gpuload"
  },
  {
    "Type": "MemoryUsageSensor",
    "Id": "1cefaf94-0802-4ccf-880b-22227e9aa059",
    "UpdateInterval": 30,
    "Query": "SELECT FreePhysicalMemory,TotalVisibleMemorySize FROM Win32_OperatingSystem",
    "Scope": "",
    "WindowName": "",
    "Category": "",
    "Counter": "",
    "Instance": "",
    "Name": "sdwilsh_desktop_satellite_memoryusage"
  },
  {
    "Type": "AudioSensors",
    "Id": "db834c33-c466-485e-b1fe-b092ea920b89",
    "UpdateInterval": 20,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "",
    "Counter": "",
    "Instance": "",
    "Name": "sdwilsh_desktop_satellite_audio"
  },
  {
    "Type": "NetworkSensors",
    "Id": "2720b0d6-b475-4aff-af55-be8384abb954",
    "UpdateInterval": 30,
    "Query": "",
    "Scope": null,
    "WindowName": "",
    "Category": "",
    "Counter": "",
    "Instance": "",
    "Name": "sdwilsh_desktop_satellite_network_lan"
  }
]
```

The logs show this, which I suspect is why it's not saving the second one in the log file:
```
2022-06-26 14:40:31.090 -07:00 [INF] [SETTINGS_SENSORS] Stored 5 entities
2022-06-26 14:41:20.288 -07:00 [INF] [SENSORSMANAGER] Processing 6 received sensor(s), deleting 1 sensor(s) ..
2022-06-26 14:41:20.319 -07:00 [FTL] [SENSORSMANAGER] Error while storing: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at HASS.Agent.Satellite.Service.Sensors.SensorsManager.StoreAsync(List`1 sensors, List`1 toBeDeletedSensors)
```

If I stop, and then restart the service, unsurprisingly, it does not have the second sensor, but it is now starting and not dying.

**Comment by LAB02-Admin** [comment]
You've (possibly) tracked two bugs here!

The first one might be related to this: [#46]. It's something out of my control; some graphic cards under certain configurations can cause a hard crash of the hardware libray I'm using, taking the service down with it as well. There's not much I can do about that, I've created a ticket with the devs but nothing yet. If that's the case, you can circumvent it by removing the sensor and using a wmi solution [like this](https://github.com/LAB02-Research/HASS.Agent/issues/46#issuecomment-1138307507). 

But since you mention that it's stable now, it might be a new problem, in which case I have to investigate the `Unable to load DLL 'nvapi64.dll'` issue..

The second one is a problem with storing certain new sensors, which has been fixed in the latest beta:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta1

After you've installed this one, you should be able to add all sensors to the satellite service without problems.

> It wasn't clear that changing the logging detail of the agent would update the service too. It might be worth adding a note there.

Well currently it doesn't propagate to the service, when it's running as a service (only when launched manually). So that needs to be fixed first, afterwards I'll definitely add the note :)

Thanks for all the research!

**Comment by sdwilsh** [comment]
It looks like the beta has fixed the issue for me with the network sensor :)

Not having issues with the service crashing either.

**Comment by LAB02-Admin** [comment]
Awesome! Thanks for letting me know
